In [2]:
import numpy as np

In [5]:

A = np.array([[0.1, 0.2, 0.3],
                    [0.4, 0.5, 0.6],
                    [0.7,0.8,0.9]]) # Shape: (3,3)
B = np.array([2,1,0,1,2,0,2,0,1]) # SHape (9,)
C = A[B, :]

print("A:\n", A)
print("B:\n", B)
print("C:\n", C)

A:
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
B:
 [2 1 0 1 2 0 2 0 1]
C:
 [[0.7 0.8 0.9]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [0.1 0.2 0.3]
 [0.7 0.8 0.9]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [8]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Use the syntax array[[], :]
result = array[[], :]

print(result)  # Output: []
print(result.shape)  # Output: (0, 3)
print(result.dtype)  # Output: int64 (or int32, depending on your system)
print(type(result))  # Output: <class 'numpy.ndarray'>

[]
(0, 3)
int32
<class 'numpy.ndarray'>


In [20]:
array_1d = np.array([1, 2, 3])
print(array_1d[[]])  # Output: [], shape: (0,)
# print(array_1d[[], :])  # Raises IndexError: too many indices for array
#print(array_1d[[]].shape)  # Output: (0,)

[]


In [26]:
#Create a function that checks if a given string is a palindrome (reads the same backward as forward, ignoring case and non-alphanumeric characters).
def is_palindrome(s: str) -> bool:
    s = ''.join(c.lower() for c in s if c.isalnum())
    return s == s[::-1]
print(is_palindrome("A man, a plan, a canal: Panama"))  # True
print(is_palindrome("race a car"))  # False

True
False


In [ ]:
#Write a program that prints numbers from 1 to 100. For multiples of 3, print "Fizz" instead of the number; for multiples of 5, print "Buzz"; for multiples of both, print "FizzBuzz".

def fizzbuzz():
    for i in range(1, 101):
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)
fizzbuzz()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [ ]:
#Write a function that converts a binary number (given as an integer) to its decimal equivalent.

def binary_to_decimal(binary: int) -> int:
    decimal, i = 0, 0
    while binary != 0:
        digit = binary % 10
        decimal += digit * (2 ** i)
        binary //= 10
        i += 1
    return decimal
print(binary_to_decimal(1010))  # 10
print(binary_to_decimal(1111))  # 15

10
15


In [ ]:
#Implement a binary search algorithm to find the index of a target element in a sorted list. Return -1 if not found.

def binary_search(arr: list, target: int) -> int:
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1
print(binary_search([1, 3, 5, 7, 9], 5))  # 2
print(binary_search([1, 3, 5, 7, 9], 6))  # -1

2
-1


In [ ]:
#Given an array of integers and a target sum, find two numbers that add up to the target and return their indices.

def two_sum(nums: list, target: int) -> list:
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i
    return []
print(two_sum([2, 7, 11, 15], 9))  # [0, 1]
print(two_sum([3, 2, 4], 6))  # [1, 2]

[0, 1]
[1, 2]


In [49]:
#Find the contiguous sub array within a one-dimensional numeric array that has the largest sum.

def max_subarray_sum(nums: list) -> int:
    max_sum = current_sum = nums[0]
    for num in nums[1:]:
        current_sum = max(num, current_sum + num)
        max_sum = max(max_sum, current_sum)
    return max_sum
#print(max_subarray_sum([-2, 1, -3, 4, -1, 2, 1, -5, 4]))  # 6
print(max_subarray_sum([1.0,2.0,3.5,6.7]))  # 1
#print(max_subarray_sum([5, 4, -1, 7, 8]))  # 23
#print(max_subarray_sum([-1, -2, -3, -4]))  # -1 (the largest single element)
#print(max_subarray_sum([1, 2, 3, 4, 5]))  # 15 (the entire array)

13.2


In [41]:
# Function to find the maximum subarray sum
def maxSubarraySum(arr):
    
    # Stores the result (maximum sum found so far)
    res = arr[0]
    
    # Maximum sum of subarray ending at current position
    maxEnding = arr[0]

    for i in range(1, len(arr)):
        
        # Either extend the previous subarray or start 
        # new from current element
        maxEnding = max(maxEnding + arr[i], arr[i])
        
        # Update result if the new subarray sum is larger
        res = max(res, maxEnding)
    
    return res

if __name__ == "__main__":
    arr = [2, 3, -8, 7, -1, 2, 3]
    print(maxSubarraySum(arr))

11


In [86]:
def maxSubarraySum(arr):
    res = arr[0]
  
    # Outer loop for starting point of subarray
    for i in range(len(arr)):
        currSum = 0
      
        # Inner loop for ending point of subarray
        for j in range(i, len(arr)):
            currSum = currSum + arr[j]
          
            # Update res if currSum is greater than res
            res = max(res, currSum)
          
    return res

if __name__ == "__main__":
    arr = [2, 3, -8, 7, -1, 2, 3]
    print(maxSubarraySum(arr))

11


In [34]:
#Given a collection of intervals (e.g., [[1,3], [2,6], [8,10]]), merge overlapping intervals and return the result.

def merge_intervals(intervals: list) -> list:
    if not intervals:
        return []
    intervals.sort(key=lambda x: x[0])
    merged = [intervals[0]]
    for current in intervals[1:]:
        if current[0] <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], current[1])
        else:
            merged.append(current)
    return merged
print(merge_intervals([[1,3], [2,6], [8,10], [15,18]]))  # [[1,6], [8,10], [15,18]]

[[1, 6], [8, 10], [15, 18]]


In [35]:
#Implement DFS to traverse a graph (represented as an adjacency list) and return the order of visited nodes.

def dfs(graph: dict, start: str) -> list:
    visited = []
    def dfs_recursive(node: str):
        if node not in visited:
            visited.append(node)
            for neighbor in graph[node]:
                dfs_recursive(neighbor)
    dfs_recursive(start)
    return visited
graph = {'A': ['B', 'C'], 'B': ['A', 'D', 'E'], 'C': ['A', 'F'], 'D': ['B'], 'E': ['B', 'F'], 'F': ['C', 'E']}
print(dfs(graph, 'A'))  # ['A', 'B', 'D', 'E', 'F', 'C']

['A', 'B', 'D', 'E', 'F', 'C']


In [36]:
#Place N queens on an N×N chessboard such that no two queens threaten each other (no two queens share the same row, column, or diagonal).



def solve_n_queens(n: int) -> list:
    def is_safe(board, row, col):
        for i in range(row):
            if board[i] == col or board[i] - i == col - row or board[i] + i == col + row:
                return False
        return True
    def solve(board, row):
        if row == n:
            result.append(board[:])
            return
        for col in range(n):
            if is_safe(board, row, col):
                board[row] = col
                solve(board, row + 1)
    result = []
    solve([0] * n, 0)
    return result
print(solve_n_queens(4))  # [[2, 0, 3, 1], [1, 3, 0, 2]]

[[1, 3, 0, 2], [2, 0, 3, 1]]


In [37]:
#Write a function to solve a 9×9 Sudoku puzzle, represented as a 2D list where empty cells are 0, by filling in all cells according to Sudoku rules.


def solve_sudoku(board: list) -> bool:
    def is_valid(board, row, col, num):
        for x in range(9):
            if board[row][x] == num or board[x][col] == num:
                return False
        start_row, start_col = 3 * (row // 3), 3 * (col // 3)
        for i in range(start_row, start_row + 3):
            for j in range(start_col, start_col + 3):
                if board[i][j] == num:
                    return False
        return True
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                for num in range(1, 10):
                    if is_valid(board, i, j, num):
                        board[i][j] = num
                        if solve_sudoku(board):
                            return True
                        board[i][j] = 0
                return False
    return True
board = [
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
]
solve_sudoku(board)
for row in board:
    print(row)

[5, 3, 4, 6, 7, 8, 9, 1, 2]
[6, 7, 2, 1, 9, 5, 3, 4, 8]
[1, 9, 8, 3, 4, 2, 5, 6, 7]
[8, 5, 9, 7, 6, 1, 4, 2, 3]
[4, 2, 6, 8, 5, 3, 7, 9, 1]
[7, 1, 3, 9, 2, 4, 8, 5, 6]
[9, 6, 1, 5, 3, 7, 2, 8, 4]
[2, 8, 7, 4, 1, 9, 6, 3, 5]
[3, 4, 5, 2, 8, 6, 1, 7, 9]


In [1]:
import cmath
x = cmath.sqrt(4)  # Output: 1j (complex)
z = cmath.sqrt(3)  # Output: 2j (complex)

print(x, type(x))  # Output: (2+0j) <class 'complex'>

a, b = 5, 3
print(a + b, type(a + b))  # Output: 8 <class 'int'>


a, b = 3.5, 7.9
print(a+b, type(a+b))  # Output: 11.4 <class 'float'>)

a, b = 3.5, 7.9
y = 3.6
print(a * y, type(a * y))  # Output: 27.65 <class 'float'>

print(a + x, type(a + x))

print(x + z, type(x + z))  # Output: -4.4 <class 'float'>

print(a / b, type(a / b))  # Output: 0.4430379746835443 <class 'float'>

print(a // b, type(a // b))  # Output: 0.0 <class 'float'>


(2+0j) <class 'complex'>
8 <class 'int'>
11.4 <class 'float'>
12.6 <class 'float'>
(5.5+0j) <class 'complex'>
(3.732050807568877+0j) <class 'complex'>
0.4430379746835443 <class 'float'>
0.0 <class 'float'>


In [1]:
a, b = 5, 3
print(a + b, type(a + b))  # Output: 8 <class 'int'>

8 <class 'int'>


In [2]:
def two_sum(nums: list, target: int) -> list:
    # Dictionary to store number-to-index mapping
    seen = {}
    # Iterate through the list with index
    for i, num in enumerate(nums):
        # Calculate the complement needed to reach the target
        complement = target - num
        # If complement exists in seen, we found a pair
        if complement in seen:
            return [seen[complement], i]
        # Otherwise, add the current number and its index to seen
        seen[num] = i
    # Return empty list if no solution is found (handles edge cases)
    return []

# Test cases
print(two_sum([2, 7, 11, 15], 9))  # Output: [0, 1]
print(two_sum([3, 2, 4], 6))       # Output: [1, 2]
print(two_sum([3, 3], 6))          # Output: [0, 1]
print(two_sum([], 5))              # Output: [] (empty array case)
print(two_sum([1], 2))             # Output: [] (no solution case)

[0, 1]
[1, 2]
[0, 1]
[]
[]


In [3]:
import numpy as np
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array[[], :])  # Output: [] (shape: (0, 2))
print(two_sum([], 5))  # Output: [] (similar empty result)


# Additional test cases
print(two_sum([-1, -2, -3], -5))  # Output: [1, 2] (handles negative numbers)
print(two_sum([0, 0], 0))         # Output: [0, 1] (handles zeros)
print(two_sum([1, 2, 3], 10))     # Output: [] (no solution)

[]
[]
[1, 2]
[0, 1]
[]


In [4]:
import numpy as np

# Create a 1D array with complex numbers
complex_array = np.array([1 + 2j, 3 - 4j, 0 + 1j], dtype=complex)
print("Complex Array:", complex_array)
print("Data Type:", complex_array.dtype)
print("Sum:", np.sum(complex_array))  # Sum of complex numbers
print("Real Part:", complex_array.real)  # Extract real parts
print("Imaginary Part:", complex_array.imag)  # Extract imaginary parts

Complex Array: [1.+2.j 3.-4.j 0.+1.j]
Data Type: complex128
Sum: (4-1j)
Real Part: [1. 3. 0.]
Imaginary Part: [ 2. -4.  1.]


In [5]:
import numpy as np

# Create a 1D array with floating-point numbers
float_array = np.array([1.5, 2.7, 3.2, 0.0], dtype=float)
print("Float Array:", float_array)
print("Data Type:", float_array.dtype)
print("Sum:", np.sum(float_array))  # Sum of floats
print("Rounded:", np.round(float_array, 1))  # Round to 1 decimal place

Float Array: [1.5 2.7 3.2 0. ]
Data Type: float64
Sum: 7.4
Rounded: [1.5 2.7 3.2 0. ]


In [84]:
import numpy as np

# Empty 1D array with complex dtype
empty_complex = np.array([], dtype=complex)
print("Empty Complex Array:", empty_complex)
print("Shape:", empty_complex.shape)
print("Data Type:", empty_complex.dtype)

# Empty 1D array with float dtype
empty_float = np.array([], dtype=float)
print("Empty Float Array:", empty_float)
print("Shape:", empty_float.shape)
print("Data Type:", empty_float.dtype)

Empty Complex Array: []
Shape: (0,)
Data Type: complex128
Empty Float Array: []
Shape: (0,)
Data Type: float64


In [85]:
import numpy as np

def two_sum_numpy(nums: np.ndarray, target):
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i
    return []

# Complex numbers
complex_nums = np.array([1 + 2j, 3 - 1j, 2 + 3j], dtype=complex)
print(two_sum_numpy(complex_nums, 4 + 1j))  # Possible output: [0, 1] if 1+2j + 3-1j = 4+1j

# Float numbers
float_nums = np.array([1.5, 2.5, 3.0], dtype=float)
print(two_sum_numpy(float_nums, 4.0))  # Possible output: [0, 1] if 1.5 + 2.5 = 4.0

[0, 1]
[0, 1]


In [90]:
#write an array with sum 
def array_with_sum(target_sum: int, n: int) -> np.ndarray:
    """
    Create an array of n integers that sum up to target_sum.
    The integers are chosen such that they are evenly distributed.
    """
    
    
    if n <= 0:
        return np.array([])  # Return an empty array if n is non-positive
    
    # Calculate the base value and the remainder
    base_value = target_sum // n
    remainder = target_sum % n
    
    # Create an array with base_value and distribute the remainder
    array = np.full(n, base_value)
    for i in range(remainder):
        array[i] += 1  # Distribute the remainder evenly
    
    return array
print(array_with_sum(10, 5))  # Output: [2 2 2 2 2]
print(array_with_sum(10, 0))  # Output: []

#calculate a area of traingle


def triangle_area(base: float, height: float) -> float:
    """
    Calculate the area of a triangle given its base and height.
    
    :param base: The length of the base of the triangle.
    :param height: The height of the triangle.
    :return: The area of the triangle.
    """
    return 0.5 * base * height


print(triangle_area(5, 10))  # Output: 25.0

[2 2 2 2 2]
[]
25.0


In [91]:
import numpy as np

def two_sum_complex(nums: np.ndarray, target: complex) -> list:
    # Dictionary to store number-to-index mapping
    seen = {}
    # Iterate through the array with index
    for i, num in enumerate(nums):
        # Calculate the complement needed to reach the target
        complement = target - num
        # If complement exists in seen, we found a pair
        if complement in seen:
            return [seen[complement], i]
        # Add the current number and its index to seen
        seen[num] = i
    # Return empty list if no solution is found
    return []

# Create a 1D NumPy array with complex numbers
complex_array = np.array([1 + 2j, 3 - 1j, 2 + 3j, 4 + 0j], dtype=complex)

# Test cases
print("Array:", complex_array)
print("Data Type:", complex_array.dtype)
print("Test 1:", two_sum_complex(complex_array, 4 + 1j))  # Should find 1+2j + 3-1j = 4+1j
print("Test 2:", two_sum_complex(complex_array, 5 + 3j))  # Should find 3-1j + 2+3j = 5+3j
print("Test 3:", two_sum_complex(np.array([], dtype=complex), 1 + 1j))  # Empty array
print("Test 4:", two_sum_complex(np.array([1 + 1j], dtype=complex), 2 + 2j))  # Single element

Array: [1.+2.j 3.-1.j 2.+3.j 4.+0.j]
Data Type: complex128
Test 1: [0, 1]
Test 2: []
Test 3: []
Test 4: []


In [3]:
# Taking input
a = input("Enter elements separated by spaces: ").split()

# Converting list to tuple
t = tuple(a)
print(t)

('2',)


In [5]:

if __name__ == '__main__':
    n = int(input())  # Read the number of elements
    integer_list = map(int, input().split())  # Read and convert to integers
    t = tuple(integer_list)  # Create tuple from integers
    print(hash(t))  # Print hash of the tuple


-5029647727744300836


In [1]:
def print_formatted(number):
    # Width of binary representation of number (without '0b')
    width = len(bin(number)[2:])
    
    # Print for each i from 1 to number
    for i in range(1, number + 1):
        # Decimal, octal, hexadecimal (capitalized), binary
        dec = str(i).rjust(width)
        octal = oct(i)[2:].rjust(width)
        hex_cap = hex(i)[2:].upper().rjust(width)
        binary = bin(i)[2:].rjust(width)
        print(f"{dec} {octal} {hex_cap} {binary}")

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001
   18    22    12 10010
   19    23    13 10011
   20    24    14 10100


In [2]:

if __name__ == '__main__':
    thickness = int(input())  # Read thickness (odd number)
    c = 'H'  # Character for the logo
    
    # Total width of the logo is 5 * thickness
    width = 5 * thickness
    
    # Top Cone: Right-aligned triangle
    for i in range(thickness):
        print((c * (2 * i + 1)).rjust(width))  # ______ replaced with rjust
    
    # Top Pillars: Two bars of thickness rows, centered
    for i in range(thickness):
        print((c * thickness).center(width) + (c * thickness).center(width))
    
    # Middle Belt: Full width (5 * thickness) for thickness//2 + 1 rows
    for i in range((thickness + 1) // 2):
        print((c * width).center(width))
    
    # Bottom Pillars: Same as top pillars
    for i in range(thickness):
        print((c * thickness).center(width) + (c * thickness).center(width))
    
    # Bottom Cone: Left-aligned triangle
    for i in range(thickness):
        print((c * (2 * (thickness - i - 1) + 1)).ljust(width))

                                                                                                   H
                                                                                                 HHH
                                                                                               HHHHH
                                                                                             HHHHHHH
                                                                                           HHHHHHHHH
                                                                                         HHHHHHHHHHH
                                                                                       HHHHHHHHHHHHH
                                                                                     HHHHHHHHHHHHHHH
                                                                                   HHHHHHHHHHHHHHHHH
                                                                                 HHHHHHHHHH

In [3]:


if __name__ == '__main__':
    thickness = int(input())  # Read thickness (odd number)
    c = 'H'  # Character for the logo
    
    # Total width of the logo is 5 * thickness
    width = 5 * thickness
    
    # Top Cone: Right-aligned triangle
    for i in range(thickness):
        print((c * (2 * i + 1)).rjust(width))
    
    # Top Pillars: Two bars of thickness//2 rows, centered
    for i in range(thickness + 1):
        print((c * thickness).center(width) + (c * thickness).center(width))
    
    # Middle Belt: Full width (5 * thickness) for thickness rows
    for i in range(thickness // 2):
        print((c * width).center(width))
    
    # Bottom Pillars: Same as top pillars
    for i in range(thickness + 1):
        print((c * thickness).center(width) + (c * thickness).center(width))
    
    # Bottom Cone: Left-aligned triangle
    for i in range(thickness):
        print((c * (2 * (thickness - i - 1) + 1)).ljust(width))

                                                                                                   H
                                                                                                 HHH
                                                                                               HHHHH
                                                                                             HHHHHHH
                                                                                           HHHHHHHHH
                                                                                         HHHHHHHHHHH
                                                                                       HHHHHHHHHHHHH
                                                                                     HHHHHHHHHHHHHHH
                                                                                   HHHHHHHHHHHHHHHHH
                                                                                 HHHHHHHHHH

In [4]:
if __name__ == '__main__':
    s = input()
    print(any(c.isalnum() for c in s))
    print(any(c.isalpha() for c in s))
    print(any(c.isdigit() for c in s))
    print(any(c.islower() for c in s))
    print(any(c.isupper() for c in s))


True
False
True
False
False


In [9]:
import numpy as np
def rangoli(size):
    width = 4 * size - 3
    height = 2 * size - 1
    arr = np.full((height, width), '-')
    letters = [chr(97 + i) for i in range(size)]
    for i in range(size):
        row_letters = letters[size-1:size-1-i:-1] + letters[size-i-1:size]
        row_width = len(row_letters) * 2 - 1
        start = (width - row_width) // 2
        for j, c in enumerate(row_letters):
            arr[i, start + j*2] = c
            arr[height-1-i, start + j*2] = c
    return '\n'.join(''.join(row) for row in arr)
if __name__ == '__main__':
    n = int(input())
    print(rangoli(n))

----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----


In [14]:

def rangoli(size):
    # Letters from a to the nth letter (e.g., n=5 -> 'a' to 'e')
    letters = [chr(97 + i) for i in range(size)]  # 97 = ord('a')
    # Width of the rangoli: 4n-3 (e.g., n=5 -> 17)
    width = 4 * size - 3
    lines = []
    
    # Generate rows (0 to size-1 for top half, then size-2 to 0 for bottom)
    for i in range(size):
        # Letters for this row: from index size-1 down to size-1-i, then back
        row_letters = letters[size-1:size-1-i:-1] + letters[size-i-1:size]
        # Join with hyphens and center with spaces
        row = '-'.join(row_letters).center(width, '-')
        lines.append(row)
    
    # Add bottom half (reverse of top half, excluding middle row)
    lines += lines[-2::-1]
    
    # Join lines with newlines
    return '\n'.join(lines)

if __name__ == '__main__':
    n = int(input())
    print(rangoli(n))


------------------j------------------
----------------j-i-j----------------
--------------j-i-h-i-j--------------
------------j-i-h-g-h-i-j------------
----------j-i-h-g-f-g-h-i-j----------
--------j-i-h-g-f-e-f-g-h-i-j--------
------j-i-h-g-f-e-d-e-f-g-h-i-j------
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
j-i-h-g-f-e-d-c-b-a-b-c-d-e-f-g-h-i-j
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
------j-i-h-g-f-e-d-e-f-g-h-i-j------
--------j-i-h-g-f-e-f-g-h-i-j--------
----------j-i-h-g-f-g-h-i-j----------
------------j-i-h-g-h-i-j------------
--------------j-i-h-i-j--------------
----------------j-i-j----------------
------------------j------------------


In [17]:
def rangoli(size):
    alphabet = [chr(ord('a') + i) for i in range(size)]
    
    lines = []
    # Generate the upper part of the rangoli (including the middle line)
    for i in range(size):
        # Characters for the current line
        # Example for size=5, i=0: ['e']
        # Example for size=5, i=1: ['e', 'd', 'e']
        # Example for size=5, i=4: ['e', 'd', 'c', 'b', 'a', 'b', 'c', 'd', 'e']
        current_chars = alphabet[size-1:size-1-i:-1] + alphabet[size-i-1:size]
        
        # Join characters with hyphens
        line_str = "-".join(current_chars)
        
        # Calculate total width of the rangoli
        # The widest line (middle line) has (2*size - 1) characters and (2*size - 2) hyphens
        # So, total width = (2*size - 1) + (2*size - 2) = 4*size - 3
        total_width = (size * 4) - 3
        
        # Center the line with hyphens
        centered_line = line_str.center(total_width, '-')
        lines.append(centered_line)
    
    # The full rangoli is the upper part + the reverse of the upper part (excluding the middle line)
    full_rangoli = lines[:-1] + lines[::-1]
    
    return "\n".join(full_rangoli)

if __name__ == '__main__':
    n = int(input())
    print(rangoli(n))

--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


In [19]:
def rangoli(size):
    """
    Generates an alphabet rangoli pattern of a given size.

    The rangoli pattern is centered with 'a' at its core,
    and expands outwards to the 'size'-th alphabet character.

    Args:
        size (int): The size of the rangoli.

    Returns:
        str: A single string made up of each of the lines of the rangoli
             separated by a newline character (\n).
    """
    # Create a list of alphabet characters from 'a' up to the character
    # corresponding to the given size.
    # For size=5, alphabet will be ['a', 'b', 'c', 'd', 'e']
    alphabet = [chr(ord('a') + i) for i in range(size)]

    lines = []
    # Generate the upper part of the rangoli, including the middle line.
    # The loop runs from i = 0 to size - 1.
    for i in range(size):
        # Construct the characters for the current line.
        # This involves two parts:
        # 1. Descending sequence: from alphabet[size-1] down to alphabet[size-1-i]
        #    Example for size=5, i=1: alphabet[4:3:-1] -> ['e', 'd']
        # 2. Ascending sequence: from alphabet[size-i-1] up to alphabet[size-1]
        #    (excluding the first element to avoid duplication with the descending part)
        #    Example for size=5, i=1: alphabet[3:5] -> ['d', 'e']
        # Combined for size=5, i=1: ['e', 'd'] + ['e'] = ['e', 'd', 'e']
        current_chars_desc = alphabet[size-1:size-1-i:-1]
        current_chars_asc = alphabet[size-i:size] # Start from size-i to exclude the center char if i > 0

        current_chars = current_chars_desc + current_chars_asc

        # Join the characters with hyphens to form the raw line string.
        line_str = "-".join(current_chars)

        # Calculate the total width of the rangoli.
        # The widest line (the middle line) has (2 * size - 1) characters
        # and (2 * size - 2) hyphens.
        # Total width = (2 * size - 1) + (2 * size - 2) = 4 * size - 3.
        total_width = (size * 4) - 3

        # Center the line string within the total width, padding with hyphens.
        centered_line = line_str.center(total_width, '-')
        lines.append(centered_line)

    # The complete rangoli pattern is formed by:
    # 1. The lines generated in the loop (upper half including the middle line).
    # 2. The reverse of the lines generated in the loop (lower half),
    #    excluding the first line (which is the middle line, already included).
    #    lines[:-1] gets all lines except the last one (the middle line).
    #    lines[::-1] reverses the entire list of lines.
    full_rangoli = lines[:-1] + lines[::-1]

    # Join all the lines with newline characters to form the final output string.
    return "\n".join(full_rangoli)

# Example usage (as per sample input):
size_input = 10
print(rangoli(size_input))

-------------------------------------
-----------------j-j-----------------
---------------j-i-i-j---------------
-------------j-i-h-h-i-j-------------
-----------j-i-h-g-g-h-i-j-----------
---------j-i-h-g-f-f-g-h-i-j---------
-------j-i-h-g-f-e-e-f-g-h-i-j-------
-----j-i-h-g-f-e-d-d-e-f-g-h-i-j-----
---j-i-h-g-f-e-d-c-c-d-e-f-g-h-i-j---
-j-i-h-g-f-e-d-c-b-b-c-d-e-f-g-h-i-j-
---j-i-h-g-f-e-d-c-c-d-e-f-g-h-i-j---
-----j-i-h-g-f-e-d-d-e-f-g-h-i-j-----
-------j-i-h-g-f-e-e-f-g-h-i-j-------
---------j-i-h-g-f-f-g-h-i-j---------
-----------j-i-h-g-g-h-i-j-----------
-------------j-i-h-h-i-j-------------
---------------j-i-i-j---------------
-----------------j-j-----------------
-------------------------------------


In [20]:

def rangoli(size):
    # Letters from a to the nth letter (e.g., n=5 -> 'a' to 'e')
    letters = [chr(97 + i) for i in range(size)]  # 97 = ord('a')
    # Width of the rangoli: 4n-3 (e.g., n=5 -> 17)
    width = 4 * size - 3
    lines = []
    
    # Generate rows (0 to size-1 for top half, then size-2 to 0 for bottom)
    for i in range(size):
        # Letters for this row: from index size-1 down to size-1-i, then back
        row_letters = letters[size-1:size-1-i:-1] + letters[size-i-1:size]
        # Join with hyphens and center with spaces
        row = '-'.join(row_letters).center(width, '-')
        lines.append(row)
    
    # Add bottom half (reverse of top half, excluding middle row)
    lines += lines[-2::-1]
    
    # Join lines with newlines
    return print('\n'.join(lines))

if __name__ == '__main__':
    n = int(input())
    rangoli(n)


--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


In [ ]:
def solve(s):
    """
    Capitalizes a full name according to specific rules:
    - The first letter of each word (separated by spaces) is capitalized.
    - If a word starts with a non-alphabetic character (e.g., number, symbol),
      that word remains unchanged.

    Args:
        s (str): The full name string.

    Returns:
        str: The capitalized string.
    """
    result_chars = []
    # Flag to determine if the next character should be capitalized.
    # It's True at the beginning of the string or after a space.
    capitalize_next = True

    for char in s:
        if char == ' ':
            # If the character is a space, append it and set the flag
            # to True for the next character (start of a new word).
            result_chars.append(char)
            capitalize_next = True
        else:
            if capitalize_next and char.isalpha():
                # If it's the start of a word and the character is an alphabet,
                # capitalize it.
                result_chars.append(char.upper())
                capitalize_next = False # Reset flag as the first char of word is processed
            else:
                # Otherwise (not the start of a word, or not an alphabet),
                # append the character as is.
                result_chars.append(char)
                capitalize_next = False # Reset flag as the first char of word is processed

    return "".join(result_chars)

# Sample Input:
name = "chris alan"
print(solve(name)) # Expected Output: Chris Alan

# Another test case based on the problem description:
# name_with_number = "12abc"
# print(solve(name_with_number)) # Expected Output: 12abc

# Test with mixed case and multiple spaces:
# name_mixed = "alison heck 123test #hello world"
# print(solve(name_mixed)) # Expected Output: Alison Heck 123test #hello World

# Test with leading/trailing spaces:
# name_spaces = "  leading and trailing  "
# print(solve(name_spaces)) # Expected Output:   Leading And Trailing


#if __name__ == '__main__':
#    fptr = open(os.environ['OUTPUT_PATH'], 'w')

#    s = input()

#    result = solve(s)

#    fptr.write(result + '\n')

#    fptr.close()


Chris Alan
