In [2]:
import numpy as np

In [5]:

A = np.array([[0.1, 0.2, 0.3],
                    [0.4, 0.5, 0.6],
                    [0.7,0.8,0.9]]) # Shape: (3,3)
B = np.array([2,1,0,1,2,0,2,0,1]) # SHape (9,)
C = A[B, :]

print("A:\n", A)
print("B:\n", B)
print("C:\n", C)

A:
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
B:
 [2 1 0 1 2 0 2 0 1]
C:
 [[0.7 0.8 0.9]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [0.1 0.2 0.3]
 [0.7 0.8 0.9]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [8]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Use the syntax array[[], :]
result = array[[], :]

print(result)  # Output: []
print(result.shape)  # Output: (0, 3)
print(result.dtype)  # Output: int64 (or int32, depending on your system)
print(type(result))  # Output: <class 'numpy.ndarray'>

[]
(0, 3)
int32
<class 'numpy.ndarray'>


In [ ]:
array_1d = np.array([1, 2, 3])
print(array_1d[[]])  # Output: [], shape: (0,)
# print(array_1d[[], :])  # Raises IndexError: too many indices for array
print(array_1d[[0]].shape)  # Output: (0,)

[]
(1,)
