In [2]:
import numpy as np

In [5]:

A = np.array([[0.1, 0.2, 0.3],
                    [0.4, 0.5, 0.6],
                    [0.7,0.8,0.9]]) # Shape: (3,3)
B = np.array([2,1,0,1,2,0,2,0,1]) # SHape (9,)
C = A[B, :]

print("A:\n", A)
print("B:\n", B)
print("C:\n", C)

A:
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
B:
 [2 1 0 1 2 0 2 0 1]
C:
 [[0.7 0.8 0.9]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [0.1 0.2 0.3]
 [0.7 0.8 0.9]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [8]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Use the syntax array[[], :]
result = array[[], :]

print(result)  # Output: []
print(result.shape)  # Output: (0, 3)
print(result.dtype)  # Output: int64 (or int32, depending on your system)
print(type(result))  # Output: <class 'numpy.ndarray'>

[]
(0, 3)
int32
<class 'numpy.ndarray'>


In [20]:
array_1d = np.array([1, 2, 3])
print(array_1d[[]])  # Output: [], shape: (0,)
# print(array_1d[[], :])  # Raises IndexError: too many indices for array
#print(array_1d[[]].shape)  # Output: (0,)

[]


In [26]:
#Create a function that checks if a given string is a palindrome (reads the same backward as forward, ignoring case and non-alphanumeric characters).
def is_palindrome(s: str) -> bool:
    s = ''.join(c.lower() for c in s if c.isalnum())
    return s == s[::-1]
print(is_palindrome("A man, a plan, a canal: Panama"))  # True
print(is_palindrome("race a car"))  # False

True
False


In [ ]:
#Write a program that prints numbers from 1 to 100. For multiples of 3, print "Fizz" instead of the number; for multiples of 5, print "Buzz"; for multiples of both, print "FizzBuzz".

def fizzbuzz():
    for i in range(1, 101):
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)
fizzbuzz()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [ ]:
#Write a function that converts a binary number (given as an integer) to its decimal equivalent.

def binary_to_decimal(binary: int) -> int:
    decimal, i = 0, 0
    while binary != 0:
        digit = binary % 10
        decimal += digit * (2 ** i)
        binary //= 10
        i += 1
    return decimal
print(binary_to_decimal(1010))  # 10
print(binary_to_decimal(1111))  # 15

10
15


In [ ]:
#Implement a binary search algorithm to find the index of a target element in a sorted list. Return -1 if not found.

def binary_search(arr: list, target: int) -> int:
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1
print(binary_search([1, 3, 5, 7, 9], 5))  # 2
print(binary_search([1, 3, 5, 7, 9], 6))  # -1

2
-1


In [ ]:
#Given an array of integers and a target sum, find two numbers that add up to the target and return their indices.

def two_sum(nums: list, target: int) -> list:
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i
    return []
print(two_sum([2, 7, 11, 15], 9))  # [0, 1]
print(two_sum([3, 2, 4], 6))  # [1, 2]

[0, 1]
[1, 2]


In [49]:
#Find the contiguous sub array within a one-dimensional numeric array that has the largest sum.

def max_subarray_sum(nums: list) -> int:
    max_sum = current_sum = nums[0]
    for num in nums[1:]:
        current_sum = max(num, current_sum + num)
        max_sum = max(max_sum, current_sum)
    return max_sum
#print(max_subarray_sum([-2, 1, -3, 4, -1, 2, 1, -5, 4]))  # 6
print(max_subarray_sum([1.0,2.0,3.5,6.7]))  # 1
#print(max_subarray_sum([5, 4, -1, 7, 8]))  # 23
#print(max_subarray_sum([-1, -2, -3, -4]))  # -1 (the largest single element)
#print(max_subarray_sum([1, 2, 3, 4, 5]))  # 15 (the entire array)

13.2


In [41]:
# Function to find the maximum subarray sum
def maxSubarraySum(arr):
    
    # Stores the result (maximum sum found so far)
    res = arr[0]
    
    # Maximum sum of subarray ending at current position
    maxEnding = arr[0]

    for i in range(1, len(arr)):
        
        # Either extend the previous subarray or start 
        # new from current element
        maxEnding = max(maxEnding + arr[i], arr[i])
        
        # Update result if the new subarray sum is larger
        res = max(res, maxEnding)
    
    return res

if __name__ == "__main__":
    arr = [2, 3, -8, 7, -1, 2, 3]
    print(maxSubarraySum(arr))

11


In [40]:
def maxSubarraySum(arr):
    res = arr[0]
  
    # Outer loop for starting point of subarray
    for i in range(len(arr)):
        currSum = 0
      
        # Inner loop for ending point of subarray
        for j in range(i, len(arr)):
            currSum = currSum + arr[j]
          
            # Update res if currSum is greater than res
            res = max(res, currSum)
          
    return res

if __name__ == "__main__":
    arr = [2, 3, -8, 7, -1, 2, 3]
    print(maxSubarraySum(arr))

11


In [34]:
#Given a collection of intervals (e.g., [[1,3], [2,6], [8,10]]), merge overlapping intervals and return the result.

def merge_intervals(intervals: list) -> list:
    if not intervals:
        return []
    intervals.sort(key=lambda x: x[0])
    merged = [intervals[0]]
    for current in intervals[1:]:
        if current[0] <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], current[1])
        else:
            merged.append(current)
    return merged
print(merge_intervals([[1,3], [2,6], [8,10], [15,18]]))  # [[1,6], [8,10], [15,18]]

[[1, 6], [8, 10], [15, 18]]


In [35]:
#Implement DFS to traverse a graph (represented as an adjacency list) and return the order of visited nodes.

def dfs(graph: dict, start: str) -> list:
    visited = []
    def dfs_recursive(node: str):
        if node not in visited:
            visited.append(node)
            for neighbor in graph[node]:
                dfs_recursive(neighbor)
    dfs_recursive(start)
    return visited
graph = {'A': ['B', 'C'], 'B': ['A', 'D', 'E'], 'C': ['A', 'F'], 'D': ['B'], 'E': ['B', 'F'], 'F': ['C', 'E']}
print(dfs(graph, 'A'))  # ['A', 'B', 'D', 'E', 'F', 'C']

['A', 'B', 'D', 'E', 'F', 'C']


In [36]:
#Place N queens on an N×N chessboard such that no two queens threaten each other (no two queens share the same row, column, or diagonal).



def solve_n_queens(n: int) -> list:
    def is_safe(board, row, col):
        for i in range(row):
            if board[i] == col or board[i] - i == col - row or board[i] + i == col + row:
                return False
        return True
    def solve(board, row):
        if row == n:
            result.append(board[:])
            return
        for col in range(n):
            if is_safe(board, row, col):
                board[row] = col
                solve(board, row + 1)
    result = []
    solve([0] * n, 0)
    return result
print(solve_n_queens(4))  # [[2, 0, 3, 1], [1, 3, 0, 2]]

[[1, 3, 0, 2], [2, 0, 3, 1]]


In [37]:
#Write a function to solve a 9×9 Sudoku puzzle, represented as a 2D list where empty cells are 0, by filling in all cells according to Sudoku rules.


def solve_sudoku(board: list) -> bool:
    def is_valid(board, row, col, num):
        for x in range(9):
            if board[row][x] == num or board[x][col] == num:
                return False
        start_row, start_col = 3 * (row // 3), 3 * (col // 3)
        for i in range(start_row, start_row + 3):
            for j in range(start_col, start_col + 3):
                if board[i][j] == num:
                    return False
        return True
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                for num in range(1, 10):
                    if is_valid(board, i, j, num):
                        board[i][j] = num
                        if solve_sudoku(board):
                            return True
                        board[i][j] = 0
                return False
    return True
board = [
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
]
solve_sudoku(board)
for row in board:
    print(row)

[5, 3, 4, 6, 7, 8, 9, 1, 2]
[6, 7, 2, 1, 9, 5, 3, 4, 8]
[1, 9, 8, 3, 4, 2, 5, 6, 7]
[8, 5, 9, 7, 6, 1, 4, 2, 3]
[4, 2, 6, 8, 5, 3, 7, 9, 1]
[7, 1, 3, 9, 2, 4, 8, 5, 6]
[9, 6, 1, 5, 3, 7, 2, 8, 4]
[2, 8, 7, 4, 1, 9, 6, 3, 5]
[3, 4, 5, 2, 8, 6, 1, 7, 9]


In [65]:
import cmath
x = cmath.sqrt(4)  # Output: 1j (complex)
print(x, type(x))  # Output: (2+0j) <class 'complex'>

a, b = 5, 3
print(a + b, type(a + b))  # Output: 8 <class 'int'>


a, b = 3.5, 7.9
print(a+b, type(a+b))  # Output: 11.4 <class 'float'>)

a, b = 3.5, 7.9
y = 3.6
print(a * y, type(a * y))  # Output: 27.65 <class 'float'>

print(a + x, type(a + x))

print(a / b, type(a / b))  # Output: 0.4430379746835443 <class 'float'>

print(a // b, type(a // b))  # Output: 0.0 <class 'float'>


(2+0j) <class 'complex'>
8 <class 'int'>
11.4 <class 'float'>
12.6 <class 'float'>
(5.5+0j) <class 'complex'>
0.4430379746835443 <class 'float'>
0.0 <class 'float'>


In [ ]:
def max_subarray_sum(nums: list) -> float:


    x = cmath.sqrt(4)
    y = cmath.sqrt(9)
    print(x, y, type(x), type(y))  # Output: (2+0j) (3+0j) <class 'complex'> <class 'complex'>
    max_sum = current_sum = nums[0]
    for num in nums[1:]:
        current_sum = max(num, current_sum + num)
        max_sum = max(max_sum, current_sum)
    return max_sum

print(max_subarray_sum([3.5,9.6,8.7]))  # 6

21.799999999999997
