In [1]:
n = int(input())

arr = list(map(int, input().split()))

print(*reversed(arr))


3


In [2]:
(lambda x: print(*reversed(list(map(int,input().split())))))(input())

4


In [ ]:
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

#creating a rank 5 array
arr = np.array([1, 2, 3, 4, 5], ndmin = 5)
print(arr)



[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]
[[[[[1 2 3 4 5]]]]]


In [1]:
import numpy as np

random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 2)
randint_array = np.random.randint(1, 10, size=(2, 3))  

print(random_array)
print(normal_array)
print(randint_array)

[[0.11260894 0.70597227 0.0251086 ]
 [0.2287427  0.32352788 0.42516848]]
[[0.5844326  0.17037514]
 [1.26422531 0.4271048 ]]
[[9 6 5]
 [4 1 6]]
