In [1]:
import scipy
print(scipy.__version__)

1.13.1


In [3]:
import numpy as np

from scipy import stats
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mean_val = np.mean(data)
std_dev = np.std(data)
t_stat, p_value = stats.ttest_1samp(data, popmean=5)
print("t_stat:", t_stat)
print("p_value:", p_value)

t_stat: 0.0
p_value: 1.0


In [10]:
import numpy as np
A = [[1, 2,],
     [5, 6,]]
B = [[3, 4],
     [7, 8]]
C = np.dot(A, B)
print(C)


[[17 20]
 [57 68]]


In [11]:
from scipy import linalg
A = [[1, 2,],
     [5, 6,]]

linalg.det(A)

-4.0

In [13]:
P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)
print(np.dot(L, U))

##CELL:
from scipy import linalg
A = [[1, 2,],
     [5, 6,]]
B = [[3, 4],
     [7, 8]]
print(linalg.solve(A, B))

[[0. 1.]
 [1. 0.]]
[[1.  0. ]
 [0.2 1. ]]
[[5.  6. ]
 [0.  0.8]]
[[5. 6.]
 [1. 2.]]
[[-1. -2.]
 [ 2.  3.]]


In [14]:
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)
print(eigen_vectors)

[-0.53112887+0.j  7.53112887+0.j]
[[-0.79402877 -0.2928046 ]
 [ 0.60788018 -0.9561723 ]]


In [15]:
v = np.array([[2, 4],[3,8]])
print(v)
s = linalg.solve(A,v)
print(s)

[[2 4]
 [3 8]]
[[-1.5  -2.  ]
 [ 1.75  3.  ]]


In [16]:
from scipy import sparse
A = sparse.lil_matrix((1000, 1000))
print(A)
A[0, :100] = np.random.rand(100)
A[1, 100:200] = A[0, :100]
A.setdiag(np.random.rand(1000))
print(A)


  (0, 0)	0.06519891004400213
  (0, 1)	0.45904365877736697
  (0, 2)	0.07331839133361284
  (0, 3)	0.4801654588419211
  (0, 4)	0.3285796532061628
  (0, 5)	0.733187797367513
  (0, 6)	0.6229120079265993
  (0, 7)	0.009384641632988244
  (0, 8)	0.3403780841530828
  (0, 9)	0.9138776068123426
  (0, 10)	0.8504777198993012
  (0, 11)	0.6544719620836233
  (0, 12)	0.7940442339368847
  (0, 13)	0.5485647067087215
  (0, 14)	0.170503096856212
  (0, 15)	0.6901651832907325
  (0, 16)	0.2587894066684836
  (0, 17)	0.3501796832893622
  (0, 18)	0.6814173248503378
  (0, 19)	0.47027765921752096
  (0, 20)	0.7612635679920459
  (0, 21)	0.8720697953168839
  (0, 22)	0.5367969378790425
  (0, 23)	0.15310466079481588
  (0, 24)	0.7939335480780357
  (0, 25)	0.9125211032550709
  (0, 26)	0.46946965638149385
  (0, 27)	0.4582601983640783
  (0, 28)	0.6193723184891669
  (0, 29)	0.012485371158459047
  (0, 30)	0.9956221291461415
  (0, 31)	0.43019224093060193
  (0, 32)	0.642381967970138
  (0, 33)	0.9952426041700027
  (0, 34)	0.672

In [17]:
from scipy.sparse import linalg
A.tocsr()
A = A.tocsr()
b = np.random.rand(1000)
ans = linalg.spsolve(A, b)
print(ans)

[ 8.93806742e+02 -3.80978747e+02  1.88544184e-02  8.65013642e-01
  2.06386810e+00  6.06972923e+00  2.43039074e+00  4.31798583e+00
  7.95672706e-01  1.91606004e+00  1.46620154e+00  1.24144606e+00
  4.59291597e+00  1.25583740e+01  3.07855259e+00  7.67706201e-01
  8.45230304e-01  2.66804544e+00  6.55862213e-01  1.49546510e-01
  2.70047097e+00  7.58608752e-01  4.24340752e+00  6.21978112e-01
  2.96070815e-01  3.18991098e-01  2.96353883e+00  3.11862603e-01
  1.68218232e+00  1.21393982e-01  2.63836289e+00  1.81899559e+00
  1.14822006e+00  3.65607970e-02  1.73905782e-01  7.52117602e-01
  6.49500888e-01  1.04047936e+00  4.91119775e-01  6.85780892e-02
  1.21157987e+00  1.64567269e+00  5.12193056e+01  7.73814341e-01
  3.18639729e+00  8.87819188e-01  4.10911008e-01  1.75208752e+00
  2.74324348e-01  8.13596494e-01  1.24930407e+00  2.51821288e-01
  1.94305287e+00  2.65297612e+00  1.36114347e+00  1.04491142e+00
  1.30031890e+00  4.06999806e+00  6.89735858e-01  6.07294471e-01
  9.24741840e-02  1.74142