In [1]:
# Importing the numpy module for numpy array
import numpy as npy

# Importing the scipy.stats.norm
from scipy.stats import norm

# calculating the cdf for the numpy array
print(norm.cdf(npy.array([-2, 0, 2])))

[0.02275013 0.5        0.97724987]


In [2]:
# importing the required package
from scipy.stats import circmean

# calculating the circular mean
print(circmean([0.4, 2.4, 3.6], high=4, low=2))
#                    |              |         |
#               -------------  ------------  ------------
#               sample array   higher bound  lower bound

2.254068341376122


In [3]:
# importing the required package
from scipy.stats.contingency import crosstab

# list p
a = ['A', 'B', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'B']

# list q
p = ['P', 'P', 'P', 'Q', 'R', 'R', 'Q', 'Q', 'R', 'R']

# result ndarray
print(crosstab(a, p))

# using the crosstab function and extracting
# the informations like - a's unique values,
# b's unique values and the final count of the pairs.
(auv, puv), cnt = crosstab(a,  p)

# printing list a's unique values
print(auv)

# printing list p's unique values
print(puv)

# printing the count object which tells us
# the pairs count for each unique values of a and p.
print(cnt)

CrosstabResult(elements=(array(['A', 'B'], dtype='<U1'), array(['P', 'Q', 'R'], dtype='<U1')), count=array([[2, 3, 0],
       [1, 0, 4]]))
['A' 'B']
['P' 'Q' 'R']
[[2 3 0]
 [1 0 4]]


In [4]:
# importing the stats and numpy module
from scipy import stats as st
import numpy as npy

# ID input array
array = npy.array([10, 20, 30, 40, 50, 60, 70, 80])

# calling the describe function
print(st.describe(array))

DescribeResult(nobs=8, minmax=(10, 80), mean=45.0, variance=600.0, skewness=0.0, kurtosis=-1.2380952380952381)


In [5]:
# importing the stats and numpy module
from scipy import stats as st
import numpy as npy

# 2D array
nd = npy.array([[5, 6], [2, 3], [5, 5],\
                [7, 9], [9, 8], [8, 7]])

# calling the describe function
print(st.describe(nd))

DescribeResult(nobs=6, minmax=(array([2, 3]), array([9, 9])), mean=array([6.        , 6.33333333]), variance=array([6.4       , 4.66666667]), skewness=array([-0.40594941, -0.3380617 ]), kurtosis=array([-0.9140625, -0.96     ]))


In [6]:
# importing the stats module
from scipy import stats as st

# the random dataset
dataset = st.norm.rvs(size=88)

# calling the kurtosis function
print(st.kurtosis(dataset))

0.2969789087334558


In [7]:
# importing the stats module
from scipy import stats as st

# the random 1D ARRAY ( dataset )
dataset = [0.02, 0.5, 0.01, 0.33, 0.51, 1.0, 0.03]

# the random 2D ARRAY ( dataset )
nd = [[5.1, 6.1], [2.1, 3.1], [5.1, 5.1],\
      [7.1, 9.1], [9.1, 8.1], [8.1, 7.1]]

# calling the kurtosis function
# 1D dataset
print(st.zscore(dataset))

# calling the kurtosis function
# 2D dataset
print(st.zscore(nd))

[-0.95649434  0.46555034 -0.98612027 -0.03809048  0.49517627  1.94684689
 -0.92686841]
[[-0.4330127  -0.16903085]
 [-1.73205081 -1.69030851]
 [-0.4330127  -0.6761234 ]
 [ 0.4330127   1.35224681]
 [ 1.29903811  0.84515425]
 [ 0.8660254   0.3380617 ]]


In [8]:
# importing the stats module
from scipy import stats as st

# ID input array
array = [99, 10, 30, 55, 50, 0, 90, 0]

# calling the skew function
print(st.skew(array))

0.3260023450293658


In [9]:
# importing the stats module
from scipy import stats as st

# sample input array
array = [[2, 3], [3, 1], [1, 3],\
         [3, 3], [4, 2], [4, 4],\
         [1, 2], [5, 6]]

# calling the mode function
print(st.mode(array))

ModeResult(mode=array([1, 3], dtype=int64), count=array([2, 3], dtype=int64))


In [10]:
# importing the stats module
from scipy import stats as st

# sample input array
array = [2, 3, 15, 1, 6, 9, 8, 4, 5, 10]

# calling the function
print(st.rankdata(array))

[ 2.  3. 10.  1.  6.  8.  7.  4.  5.  9.]
