In [1]:
import numpy as np

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

b = np.empty(2, dtype = int)
print("Matrix b : \n", b)


Matrix a : 
 [[ 1778347931   900580023]
 [-1414805773  -183852065]]
Matrix b : 
 [1065353216 1065353216]


In [4]:
import numpy as np

a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)
  
c = np.zeros([3, 3])
print("\nMatrix c : \n", c)


Matrix a : 
 [[0 0]
 [0 0]]
Matrix b : 
 [0 0]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Python Programming illustrating
# numpy.empty method

import numpy as geek

b = geek.empty(2, dtype = int)
print("Matrix b : \n", b)

a = geek.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = geek.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np 
# Create a 2x3 array in C-order
e = np.zeros((2, 3), order='C')
print("C-order array:", e)

# Create a 2x3 array in F-order
f = np.zeros((2, 3), order='F')
print("F-order array:", f)

C-order array: [[0. 0. 0.]
 [0. 0. 0.]]
F-order array: [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np

# Creating a 2D array with 3 rows and 4 columns
arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
import numpy as np 

# Create an array of tuples with zeros
d = np.zeros((2, 2), dtype=[('f', 'f4'), ('i', 'i4')])
print(d)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


In [9]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = a+b
print(add_ans)

add_ans = np.add(a, b)
print(add_ans)

c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [10]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

sub_ans = a-b
print(sub_ans)

sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]
[ 3 67  3 70]


In [11]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mul_ans = a*b
print(mul_ans)

mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]
[  10  360  130 3000]


In [12]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

div_ans = a/b
print(div_ans)

div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [13]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = np.add(a, b)
print(add_ans)

[  7  77  23 130]


In [14]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]


In [15]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]


In [16]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [17]:
import numpy as np
 
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

pow_ans = np.power(a, b)
print(pow_ans)

[        25 1934917632  419538377          0]


In [18]:
import numpy as np
 
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]


In [19]:
import numpy as np

a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)

newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [20]:
import numpy as np

a = np.arange(20)
print("\n Array is:\n ",a)

print("\n a[-8:17:1] = ",a[-8:17:1])

print("\n a[10:] = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1] =  [12 13 14 15 16]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


In [21]:
import numpy as np

a = np.arange(20)
print("\n Array is:\n ",a)

print("\n a[-8:17:1] = ",a[-8:17:1])

print("\n a[10:] = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1] =  [12 13 14 15 16]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


In [22]:
import numpy as np

macros = np.array([
    [0.8, 2.9, 3.9],
    [52.4, 23.6, 36.5],
    [55.2, 31.7, 23.9],
    [14.4, 11, 4.9]
])

cal_per_macro = np.array([3, 3, 8])

result = macros * cal_per_macro

print(result)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


In [23]:
import numpy as np

v = np.array([12, 24, 36])
w = np.array([45, 55])

print(np.reshape(v, (3, 1)) * w)

X = np.array([[12, 22, 33], [45, 55, 66]])

print(X + v)

print((X.T + w).T)

print(X * 2)

[[ 540  660]
 [1080 1320]
 [1620 1980]]
[[ 24  46  69]
 [ 57  79 102]]
[[ 57  67  78]
 [100 110 121]]
[[ 24  44  66]
 [ 90 110 132]]


In [25]:
import pandas as pd
import numpy as np

ser = pd.Series(dtype="object")

print(ser)

data = np.array(['a', 'e', 'i', 'o', 'u'])

ser = pd.Series(data)
print(ser)

Series([], dtype: object)
0    a
1    e
2    i
3    o
4    u
dtype: object


In [26]:
import pandas as pd

df = pd.DataFrame()
print(df)

lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']

df = pd.DataFrame(lst, columns=['Words'])

print(df)

Empty DataFrame
Columns: []
Index: []
    Words
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [29]:
import pandas as pd

# reading csv file 
df = pd.read_csv("people.csv")
df

First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26   
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24   
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02   
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03   
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01   

            Job Title  
0     Games developer  
1      Phytotherapist  
2           Homeopath  
3   Market researcher  
4  Veterinary surgeon

In [31]:
import pandas as pd

df = pd.read_csv("people.csv")

df.head()

First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26   
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24   
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02   
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03   
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01   

            Job Title  
0     Games developer  
1      Phytotherapist  
2           Homeopath  
3   Market researcher  
4  Veterinary surgeon

In [32]:
df = pd.read_csv("people.csv", usecols=["First Name", "Email"])
print(df)

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net


In [33]:
df = pd.read_csv("people.csv", index_col="First Name")
print(df)

           Last Name     Sex                       Email Date of birth  \
First Name                                                               
Shelby       Terrell    Male        elijah57@example.net    1945-10-26   
Phillip      Summers  Female       bethany14@example.com    1910-03-24   
Kristine      Travis    Male       bthompson@example.com    1992-07-02   
Yesenia     Martinez    Male   kaitlinkaiser@example.com    2017-08-03   
Lori            Todd    Male  buchananmanuel@example.net    1938-12-01   

                     Job Title  
First Name                      
Shelby         Games developer  
Phillip         Phytotherapist  
Kristine             Homeopath  
Yesenia      Market researcher  
Lori        Veterinary surgeon  


In [34]:
df = pd.read_csv("people.csv", na_values=["N/A", "Unknown"])

In [35]:
import pandas as pd

# Sample data stored in a multi-line string
data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

# Save the data to a CSV file
with open("sample.csv", "w") as file:
    file.write(data)
print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4


In [36]:
# Load the CSV file using pandas with multiple delimiters
df = pd.read_csv('sample.csv',
                 sep='[:, |_]',  # Define the delimiters
                 engine='python')  # Use Python engine for regex separators
df

totalbill   tip Unnamed: 2   sex smoker Unnamed: 5     day    time  \
16.99        NaN  1.01     Female    No    NaN        Sun     NaN  Dinner   
10.34        NaN  1.66        NaN  Male    NaN         No     Sun  Dinner   
21.01       3.50  Male        NaN    No    Sun        NaN  Dinner     NaN   
23.68        NaN  3.31        NaN  Male     No        NaN     Sun  Dinner   
24.59       3.61   NaN     Female    No    NaN        Sun     NaN  Dinner   
25.29        NaN  4.71       Male   NaN     No        Sun     NaN  Dinner   

       Unnamed: 8  size  
16.99         NaN   2.0  
10.34         NaN   3.0  
21.01         3.0   NaN  
23.68         NaN   2.0  
24.59         NaN   4.0  
25.29         NaN   4.0

In [37]:
df = pd.read_csv('people.csv', nrows=3)
df

First Name Last Name     Sex                  Email Date of birth  \
0     Shelby   Terrell    Male   elijah57@example.net    1945-10-26   
1    Phillip   Summers  Female  bethany14@example.com    1910-03-24   
2   Kristine    Travis    Male  bthompson@example.com    1992-07-02   

         Job Title  
0  Games developer  
1   Phytotherapist  
2        Homeopath

In [38]:
df= pd.read_csv("people.csv")
print("Previous Dataset: ")
print(df)
# using skiprows
df = pd.read_csv("people.csv", skiprows = [4,5])
print("Dataset After skipping rows: ")
print(df)

Previous Dataset: 
  First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26   
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24   
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02   
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03   
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01   

            Job Title  
0     Games developer  
1      Phytotherapist  
2           Homeopath  
3   Market researcher  
4  Veterinary surgeon  
Dataset After skipping rows: 
  First Name Last Name     Sex                  Email Date of birth  \
0     Shelby   Terrell    Male   elijah57@example.net    1945-10-26   
1    Phillip   Summers  Female  bethany14@example.com    1910-03-24   
2   Kristine    Travis    Male  bthompson@example.com    1992-07-02   

         Job Title  
0  Games developer  
1   Phytotherapist  
2 

In [39]:
df = pd.read_csv("people.csv", parse_dates=["Date of birth"])
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   First Name     5 non-null      object        
 1   Last Name      5 non-null      object        
 2   Sex            5 non-null      object        
 3   Email          5 non-null      object        
 4   Date of birth  5 non-null      datetime64[ns]
 5   Job Title      5 non-null      object        
dtypes: datetime64[ns](1), object(5)
memory usage: 372.0+ bytes
None


In [40]:
url = "https://media.geeksforgeeks.org/wp-content/uploads/20241121154629307916/people_data.csv"
df = pd.read_csv(url)
df

First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26   
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24   
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02   
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03   
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01   

            Job Title  
0     Games developer  
1      Phytotherapist  
2           Homeopath  
3   Market researcher  
4  Veterinary surgeon