<a href="https://colab.research.google.com/github/ajit-ai/Python/blob/main/numpy/LinearAlgebra/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [1, 2, 3]

# creating a 1-D list (Vertical)
list2 = [[10],
        [20],
        [30]]

# creating a vector1
# vector as row
vector1 = np.array(list1)

# creating a vector 2
# vector as column
vector2 = np.array(list2)


# showing horizontal vector
print("Horizontal Vector")
print(vector1)

print("----------------")

# showing vertical vector
print("Vertical Vector")
print(vector2)

Horizontal Vector
[1 2 3]
----------------
Vertical Vector
[[10]
 [20]
 [30]]


In [ ]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [5, 6, 9]

# creating a 1-D list (Horizontal)
list2 = [1, 2, 3]

# creating first vector
vector1 = np.array(list1)

# printing vector1
print("First Vector          : " + str(vector1))

# creating second vector
vector2 = np.array(list2)

# printing vector2
print("Second Vector         : " + str(vector2))

# adding both the vector
# a + b = (a1 + b1, a2 + b2, a3 + b3)
addition = vector1 + vector2

# printing addition vector
print("Vector Addition       : " + str(addition))

# subtracting both the vector
# a - b = (a1 - b1, a2 - b2, a3 - b3)
subtraction = vector1 - vector2

# printing addition vector
print("Vector Subtraction   : " + str(subtraction))

# multiplying  both the vector
# a * b = (a1 * b1, a2 * b2, a3 * b3)
multiplication = vector1 * vector2

# printing multiplication vector
print("Vector Multiplication : " + str(multiplication))

# dividing  both the vector
# a / b = (a1 / b1, a2 / b2, a3 / b3)
division = vector1 / vector2

# printing division vector
print("Vector Division       : " + str(division))

First Vector          : [5 6 9]
Second Vector         : [1 2 3]
Vector Addition       : [ 6  8 12]
Vector Subtraction   : [4 4 6]
Vector Multiplication : [ 5 12 27]
Vector Division       : [5. 3. 3.]


In [ ]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [5, 6, 9]

# creating a 1-D list (Horizontal)
list2 = [1, 2, 3]

# creating first vector
vector1 = np.array(list1)

# printing vector1
print("First Vector  : " + str(vector1))

# creating second vector
vector2 = np.array(list2)

# printing vector2
print("Second Vector : " + str(vector2))

# getting dot product of both the vectors
# a . b = (a1 * b1 + a2 * b2 + a3 * b3)
# a . b = (a1b1 + a2b2 + a3b3)
dot_product = vector1.dot(vector2)

# printing dot product
print("Dot Product   : " + str(dot_product))

First Vector  : [5 6 9]
Second Vector : [1 2 3]
Dot Product   : 44


In [ ]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [1, 2, 3]

# creating first vector
vector = np.array(list1)

# printing vector1
print("Vector  : " + str(vector))

# scalar value
scalar = 2

# printing scalar value
print("Scalar  : " + str(scalar))

# getting scalar multiplication value
# s * v = (s * v1, s * v2, s * v3)
scalar_mul = vector * scalar

# printing dot product
print("Scalar Multiplication : " + str(scalar_mul))

Vector  : [1 2 3]
Scalar  : 2
Scalar Multiplication : [2 4 6]


In [8]:
# importing numpy
import numpy as np

my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix




matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [7]:
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [9]:
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [10]:
my_first_matrix * my_first_matrix.I

matrix([[ 1.00000000e+00,  1.11022302e-16,  0.00000000e+00],
        [ 4.85722573e-17,  1.00000000e+00, -1.11022302e-16],
        [ 2.08166817e-17,  8.32667268e-17,  1.00000000e+00]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
right_hand_side = np.matrix([[11],
                             [22],
                             [33]])

In [13]:
my_first_inverse = my_first_matrix.I

In [15]:
solution = my_first_inverse * right_hand_side
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [16]:
my_first_matrix * solution - right_hand_side

matrix([[1.77635684e-15],
        [0.00000000e+00],
        [0.00000000e+00]])

In [17]:
# more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix, right_hand_side)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [18]:
# Compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

EigResult(eigenvalues=array([13.08576474,  2.58000566, -2.66577041]), eigenvectors=matrix([[-0.31542644, -0.95117074, -0.32372474],
        [-0.72306109,  0.30781323, -0.70222933],
        [-0.61456393,  0.02291827,  0.63409484]]))