<a href="https://colab.research.google.com/github/ajit-ai/Python/blob/main/numpy/numpy_exercise/10_Random_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [ ]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [3]:
# prompt: Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

np.random.rand(3, 2)

array([[0.15981355, 0.11007443],
       [0.1753865 , 0.65179834],
       [0.385789  , 0.59210432]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [5]:
# prompt: Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively

arr = np.random.randn(1000, 1000)
print('mean: ', arr.mean())
print('std: ', arr.std())

mean:  -0.000942535937984372
std:  0.9993654487958947




```
# This is formatted as code
```

Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [6]:
# prompt: Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

np.random.randint(0, 4, size=(3, 2))


array([[0, 0],
       [3, 0],
       [1, 2]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [7]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [8]:
# prompt: Extract 3 different integers from 0 to 9 randomly with the same probabilities.

np.random.choice(10, size=3, replace=False)

array([1, 2, 4])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [9]:
# prompt: Shuffle numbers between 0 and 9 (inclusive).

np.random.shuffle(np.arange(10))

In [ ]:
# Or


[5 2 7 4 1 0 6 8 9 3]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [10]:
# prompt:  Assign number 10 to the seed of the random generator so that you can get the same value next time.

np.random.seed(10)