<a href="https://colab.research.google.com/github/ajit-ai/Python/blob/main/numpy/numpy_exercise/12_Sorting_searching_and_counting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Soring, searching, and counting

In [83]:
import numpy as np

In [84]:
np.__version__

'2.0.2'

In [85]:
author = 'ajitjava2@gmail.com'

## Sorting

Q1. Sort x along the second axis.

In [86]:
x = np.array([[1,4],[3,1]])


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [87]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')


Q3. Get the indices that would sort x along the second axis.

In [88]:
x = np.array([[1,4],[3,1]])


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [89]:
x = np.random.permutation(10)
print("x =", x)

x = [5 1 0 2 8 4 3 9 6 7]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [90]:
x = np.random.permutation(10)
print("x =", x)

x = [2 4 3 8 7 6 5 9 1 0]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [91]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)

x = [[3 2 0 6 1]
 [5 9 8 7 4]]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [92]:
x = np.array([[np.nan, 4], [3, 2]])


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [93]:
x = np.array([[1, 2, 3], [1, 3, 5]])


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [94]:
x = np.array([[1, 2, 3], [1, 3, 5]])


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [95]:
x = np.arange(-5, 4).reshape(3, 3)


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [96]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]


## Counting

Q12. Get the number of nonzero elements in x.

In [97]:
x = [[0,1,7,0,0],[3,0,0,2,19]]


In [98]:
# Q1. Sort x along the second axis.
x = np.array([[1,4],[3,1]])
sorted_x = np.sort(x, axis=1)
print("Sorted x along the second axis:\n", sorted_x)

Sorted x along the second axis:
 [[1 4]
 [1 3]]


In [99]:
# Q3. Get the indices that would sort x along the second axis.
x = np.array([[1,4],[3,1]])
sorted_indices = np.argsort(x, axis=1)
print("Indices that would sort x along the second axis:\n", sorted_indices)

Indices that would sort x along the second axis:
 [[0 1]
 [1 0]]


In [100]:
# Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.
x = np.random.permutation(10)
print("x =", x)

sorted_x = np.sort(x)
result_array = np.zeros_like(x, dtype=float)
result_array[4] = sorted_x[4] # Fifth element (index 4)

is_fifth = np.zeros_like(x, dtype=bool)
is_fifth[4] = True
is_non_fifth = ~is_fifth
is_zero = (sorted_x == 0)

non_fifth_and_non_zero = is_non_fifth & ~is_zero
non_fifth_and_zero = is_non_fifth & is_zero

result_array[non_fifth_and_non_zero] = sorted_x[non_fifth_and_non_zero] / sorted_x[non_fifth_and_non_zero] # Should be 1.0
result_array[non_fifth_and_zero] = 0 # Set to 0 where sorted element is 0 and it's not the fifth element

print("Sorted x =", sorted_x)
print("Result array =", result_array)

x = [7 5 8 2 4 1 0 6 9 3]
Sorted x = [0 1 2 3 4 5 6 7 8 9]
Result array = [0. 1. 1. 1. 4. 1. 1. 1. 1. 1.]


In [101]:
# Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.
x = np.random.permutation(10)
print("x =", x)

sorted_indices = np.argsort(x)
print("Indices that would sort x:", sorted_indices)

# The third element (index 2) of the sorted array is x[sorted_indices[2]]
# The question asks for the indices of an array... such that its third element would be the same as the element of sorted x
# This is a bit ambiguous. It could mean:
# 1. Create an array of indices where the third index is the index of the element that would be the third element in the sorted array.
# 2. Create an array of indices where the element at the third index is the index of the element that would be the third element in the sorted array, and other elements are determined by dividing their original index by their value (which doesn't make much sense).

# Let's assume the first interpretation: Create an array of indices.
# The index of the third element in the sorted array is sorted_indices[2].
# The question then says "and it divide other elements by their value". This part is still unclear in the context of indices.
# It might be a rephrasing of the Q4 operation but applied to indices.

# Let's try to interpret it as creating an array of values based on indices and sorted values, similar to Q4 but focusing on the third element.
# Create an array of the same shape as x, but containing indices.
indices_array = np.arange(len(x), dtype=float)

# The third element (index 2) of this new array of indices should be related to the third element of the sorted x.
# Let's assume it means the value at the third index of the new array should be the index of the third element in the sorted array.
indices_array[2] = sorted_indices[2]

# "and it divide other elements by their value." - This is still very ambiguous for indices.
# If we apply the logic from Q4, it would mean for i != 2, indices_array[i] = indices_array[i] / value_of_x_at_indices_array[i]
# This interpretation doesn't seem right for an array of indices.

# Let's consider another interpretation: Create an array where the element at index i is the index in the original array x such that the element x[index] is the i-th element in the sorted version of x. This is simply argsort.
# If the question is asking to modify this argsort array:
result_indices_array = np.argsort(x)
print("Initial argsort:", result_indices_array)

# "its third element would be the same as the element of sorted x" - This doesn't fit with an array of indices.

# Let's go back to the first interpretation of creating an array of values, but the values are indices.
# Create an array initialized with indices 0 to 9.
result_array = np.arange(len(x), dtype=float)

# The third element (index 2) should be the index of the third element in the sorted x.
result_array[2] = sorted_indices[2]

# "and it divide other elements by their value." - Let's assume "value" here refers to the original index value in the result_array.
# For i != 2, result_array[i] = result_array[i] / result_array[i] (if non-zero), which would be 1.

is_third = np.zeros_like(x, dtype=bool)
is_third[2] = True
is_non_third = ~is_third
is_zero_indices = (result_array == 0)

non_third_and_non_zero_indices = is_non_third & ~is_zero_indices
non_third_and_zero_indices = is_non_third & is_zero_indices

result_array[non_third_and_non_zero_indices] = result_array[non_third_and_non_zero_indices] / result_array[non_third_and_non_zero_indices] # Should be 1.0
# Handle the case where the index itself is 0 (only at index 0) and it's not the third element.
# If index 0 is not the third element, and result_array[0] is 0, we need to set it to 0.
# This is covered by non_third_and_zero_indices.

result_array[non_third_and_zero_indices] = 0

print("Result array (interpreting 'value' as the index value):", result_array)

# This interpretation still feels a bit forced due to the "divide other elements by their value" part in the context of indices.
# Let's consider the possibility that the question is malformed or a variation of Q4.

# If it's a variation of Q4 but asking for indices:
# Create an array of indices from 0 to 9.
indices = np.arange(len(x))
# Get the indices that sort x.
sorted_indices_of_x = np.argsort(x)

# Create a result array of indices.
result_indices_array_2 = np.copy(indices)

# The third element (index 2) of this result_indices_array_2 should be the index of the third element in the sorted x.
result_indices_array_2[2] = sorted_indices_of_x[2]

# "and it divide other elements by their value." - If "value" refers to the original index value (i.e., the value in the indices array before modification).
# For i != 2, result_indices_array_2[i] = result_indices_array_2[i] / original_index_value_at_i
# This still doesn't make sense as we are dealing with indices.

# Let's assume "value" refers to the value of x at that index in the original array.
# For i != 2, result_indices_array_2[i] = result_indices_array_2[i] / x[result_indices_array_2[i]]
# This also seems unlikely.

# Given the ambiguity, and the similarity to Q4, the most plausible interpretation is that we are creating an array of values (not indices in the sense of positions in the original array), where the values are derived from the indices and the sorted array, similar to Q4.
# Let's stick with the first interpretation where we create an array of float values.

print("\nAnother interpretation attempt (closer to Q4 logic but with indices):")
# Create an array based on the sorted indices.
result_array_3 = np.copy(sorted_indices).astype(float)
print("Initial array based on sorted indices:", result_array_3)

# The third element (index 2) should be the same as the element of sorted x. This doesn't fit.

# Let's assume the question meant: Create an array where the element at index i is the index in the original array x such that x[index] is the i-th element in the sorted version of x. This is argsort.
# Then, modify this argsort array such that its third element is the index of the third element in the sorted x, and other elements are divided by their value (which is still ambiguous).

# Let's assume the question is asking to create an array of the same size as x, where the value at the third position is the index that would correspond to the third element in the sorted version of x. For other positions, the value is the original index divided by the value of x at that original index. This is highly speculative.

# Given the difficulty in interpreting "divide other elements by their value" in the context of creating an array of indices, I will provide the solution based on the most likely interpretation from Q4's logic applied to indices: create an array of float values where the third element is the index of the third element in the sorted array, and other elements are 1.0 if their original index was non-zero, and 0.0 if their original index was zero. This still feels like a stretch.

# Let's reconsider the first interpretation: Create an array of indices such that its third element is the index of the third element in the sorted array. For other positions, what should the value be? "divide other elements by their value". If "value" refers to the index value itself, this leads to the previous interpretation with 1.0s and 0.0s.

# Let's try a simpler interpretation: Create an array of indices. The third element is the index of the third element of the sorted array. Other elements are just their original indices.
result_indices_simple = np.arange(len(x))
result_indices_simple[2] = sorted_indices[2]
print("\nSimpler interpretation (third element is sorted index, others are original indices):", result_indices_simple)

# This doesn't include the "divide other elements by their value" part.

# Let's go back to the interpretation that is closest to Q4's structure. Create a float array.
result_array_q5 = np.arange(len(x), dtype=float)
result_array_q5[2] = sorted_indices[2] # Third element is the index of the third element in sorted x

# "divide other elements by their value". Let's assume "value" refers to the original index value.
is_third_q5 = np.zeros_like(x, dtype=bool)
is_third_q5[2] = True
is_non_third_q5 = ~is_third_q5
is_zero_indices_q5 = (result_array_q5 == 0)

non_third_and_non_zero_indices_q5 = is_non_third_q5 & ~is_zero_indices_q5
non_third_and_zero_indices_q5 = is_non_third_q5 & is_zero_indices_q5

# For non-third, non-zero indices, divide the index by itself (resulting in 1.0).
result_array_q5[non_third_and_non_zero_indices_q5] = result_array_q5[non_third_and_non_zero_indices_q5] / result_array_q5[non_third_and_non_zero_indices_q5]

# For non-third, zero indices (only index 0), set to 0.
result_array_q5[non_third_and_zero_indices_q5] = 0

print("\nInterpretation similar to Q4 (float array, third element is sorted index, others are 1.0 or 0.0):", result_array_q5)

# This interpretation seems the most consistent with the structure of Q4, although the phrasing is awkward for indices. I will provide this as the solution.

# Final chosen interpretation: Create a float array of size 10. The element at index 2 is the index in the original array `x` that corresponds to the third element in the sorted version of `x`. For all other indices `i`, the element is 1.0 if `i` is non-zero, and 0.0 if `i` is zero.

result_array_final = np.zeros(len(x), dtype=float)
# Get the index of the third element in the sorted version of x
index_of_third_sorted_element = np.argsort(x)[2]

# Set the element at index 2 in the result array to this index
result_array_final[2] = index_of_third_sorted_element

# For all other indices i != 2:
# If i is non-zero, the value is 1.0
# If i is zero, the value is 0.0
other_indices = np.arange(len(x)) != 2
non_zero_other_indices = other_indices & (np.arange(len(x)) != 0)
zero_other_indices = other_indices & (np.arange(len(x)) == 0) # This will only be true for index 0 if it's not the third element

result_array_final[non_zero_other_indices] = 1.0
result_array_final[zero_other_indices] = 0.0

print("\nFinal Solution based on Q4 similarity:", result_array_final)

x = [2 4 0 7 1 5 8 9 3 6]
Indices that would sort x: [2 4 0 8 1 5 9 3 6 7]
Initial argsort: [2 4 0 8 1 5 9 3 6 7]
Result array (interpreting 'value' as the index value): [0. 1. 0. 1. 1. 1. 1. 1. 1. 1.]

Another interpretation attempt (closer to Q4 logic but with indices):
Initial array based on sorted indices: [2. 4. 0. 8. 1. 5. 9. 3. 6. 7.]

Simpler interpretation (third element is sorted index, others are original indices): [0 1 0 3 4 5 6 7 8 9]

Interpretation similar to Q4 (float array, third element is sorted index, others are 1.0 or 0.0): [0. 1. 0. 1. 1. 1. 1. 1. 1. 1.]

Final Solution based on Q4 similarity: [0. 1. 0. 1. 1. 1. 1. 1. 1. 1.]


In [102]:
# Q6. Get the maximum and minimum values and their indices of x along the second axis.
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)

max_values = np.max(x, axis=1)
min_values = np.min(x, axis=1)
max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("Maximum values along the second axis:", max_values)
print("Minimum values along the second axis:", min_values)
print("Indices of maximum values along the second axis:", max_indices)
print("Indices of minimum values along the second axis:", min_indices)

x = [[7 4 2 6 1]
 [5 3 9 8 0]]
Maximum values along the second axis: [7 9]
Minimum values along the second axis: [1 0]
Indices of maximum values along the second axis: [0 2]
Indices of minimum values along the second axis: [4 4]


In [103]:
# Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.
x = np.array([[np.nan, 4], [3, 2]])
print("x =", x)

nanmax_values = np.nanmax(x, axis=1)
nanmin_values = np.nanmin(x, axis=1)

# For indices, argmax/argmin will return the index of the first non-NaN value if all are NaN in a slice.
# To get the index of the actual max/min ignoring NaNs, we can replace NaNs with -inf for argmax and +inf for argmin.
# However, np.nanargmax and np.nanargmin exist specifically for this purpose.

nanmax_indices = np.nanargmax(x, axis=1)
nanmin_indices = np.nanargmin(x, axis=1)


print("Maximum values along the second axis (ignoring NaNs):", nanmax_values)
print("Minimum values along the second axis (ignoring NaNs):", nanmin_values)
print("Indices of maximum values along the second axis (ignoring NaNs):", nanmax_indices)
print("Indices of minimum values along the second axis (ignoring NaNs):", nanmin_indices)

x = [[nan  4.]
 [ 3.  2.]]
Maximum values along the second axis (ignoring NaNs): [4. 3.]
Minimum values along the second axis (ignoring NaNs): [4. 2.]
Indices of maximum values along the second axis (ignoring NaNs): [1 0]
Indices of minimum values along the second axis (ignoring NaNs): [1 1]


In [104]:
# Q8. Get the values and indices of the elements that are bigger than 2 in x.

x = np.array([[1, 2, 3], [1, 3, 5]])
print("x =", x)

# Get a boolean mask for elements greater than 2
mask = x > 2

# Get the values using the boolean mask
values_greater_than_2 = x[mask]

# Get the indices of elements greater than 2
indices_greater_than_2 = np.argwhere(x > 2)

print("Values greater than 2:", values_greater_than_2)
print("Indices of elements greater than 2:", indices_greater_than_2)

x = [[1 2 3]
 [1 3 5]]
Values greater than 2: [3 3 5]
Indices of elements greater than 2: [[0 2]
 [1 1]
 [1 2]]


In [105]:
# Q9. Get the indices of the elements that are bigger than 2 in the flattend x.
x = np.array([[1, 2, 3], [1, 3, 5]])
print("x =", x)

# Flatten the array
flattened_x = x.flatten()
print("Flattened x:", flattened_x)

# Get the indices of elements greater than 2 in the flattened array
indices_greater_than_2_flattened = np.where(flattened_x > 2)[0]

print("Indices of elements greater than 2 in the flattened x:", indices_greater_than_2_flattened)

x = [[1 2 3]
 [1 3 5]]
Flattened x: [1 2 3 1 3 5]
Indices of elements greater than 2 in the flattened x: [2 4 5]


In [106]:
# Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.
x = np.arange(-5, 4).reshape(3, 3)
print("x =", x)

# Use np.maximum to compare elements with 0
result = np.maximum(x, 0)

print("Result:", result)

x = [[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
Result: [[0 0 0]
 [0 0 0]
 [1 2 3]]


In [107]:
# Q11. Get the indices where elements of y should be inserted to x to maintain order.
x = np.array([1, 3, 5, 7, 9]) # x needs to be a numpy array for np.searchsorted
y = np.array([0, 4, 2, 6])   # y needs to be a numpy array

indices = np.searchsorted(x, y)

print("x =", x)
print("y =", y)
print("Indices where elements of y should be inserted into x:", indices)

x = [1 3 5 7 9]
y = [0 4 2 6]
Indices where elements of y should be inserted into x: [0 2 1 3]


In [108]:
# Q12. Get the number of nonzero elements in x.
x = [[0,1,7,0,0],[3,0,0,2,19]]

# Convert the list of lists to a NumPy array
x_array = np.array(x)

# Get the number of nonzero elements
nonzero_count = np.count_nonzero(x_array)

print("x =", x)
print("Number of nonzero elements:", nonzero_count)

x = [[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]]
Number of nonzero elements: 5
