<a href="https://colab.research.google.com/github/ajit-ai/Python/blob/main/numpy/numpy_exercise/2_Array_manipulation_routines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array manipulation routines

In [2]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [6]:
# prompt: Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

x = np.ones((10, 10, 3))
x_reshaped = x.reshape(2, 150)
print(x_reshaped)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [7]:
# prompt: . Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

x = np.array([[1, 2, 3], [4, 5, 6]])
x_flattened = x.T.ravel()
x_flattened

array([1, 4, 2, 5, 3, 6])

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [9]:
# prompt: Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

# Accessing elements after flattening or reshaping
# The 5th element will be the 5th element in the flattened array.
# The original array is [[1, 2, 3], [4, 5, 6]].
# Flattened array is [1, 4, 2, 5, 3, 6].
# The 5th element is 3 (using 0-based indexing, it's element at index 4).
fifth_element = x.T.ravel()[4]
fifth_element

np.int64(3)

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [10]:
# prompt: Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).

x = np.random.rand(3, 4, 5)
x_permuted = np.transpose(x, (1, 0, 2))
x_permuted.shape

(4, 3, 5)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [11]:
# prompt: Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

x = np.random.rand(3, 4)
x_permuted = np.transpose(x, (1, 0))
x_permuted.shape

(4, 3)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [12]:
# prompt: Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

x = np.random.rand(3, 4)
x_expanded = x[:, np.newaxis, :]
x_expanded.shape

(3, 1, 4)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [13]:
# prompt: Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

x = np.random.rand(3, 4, 1)
x_squeezed = np.squeeze(x)
x_squeezed.shape

(3, 4)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [17]:
# prompt: Lex x be an array
# [[ 1 2 3]
# [ 4 5 6].
# and y be an array
# [[ 7 8 9]
# [10 11 12]].

# Concatenate along the second axis (axis=1)
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.concatenate((x, y), axis=1)

print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [18]:
# prompt:  Lex x be an array
# [[ 1 2 3]
# [ 4 5 6].
# and y be an array
# [[ 7 8 9]
# [10 11 12]].

# Concatenate along the first axis (axis=0)
z = np.concatenate((x, y), axis=0)

z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [20]:
# prompt: Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

result = np.vstack((x, y)).T
result

array([[1, 4],
       [2, 5],
       [3, 6]])

Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [21]:
# prompt: Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

x = np.array([[1],[2],[3]])
y = np.array([[4], [5], [6]])
result = np.hstack((x,y))[:, np.newaxis, :]
result

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [22]:
# prompt:  Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

x = np.arange(1, 10)
split_points = [4, 6]  # Indices after the first two splits (4 and 4+2=6)
x1, x2, x3 = np.split(x, split_points)

print(x1)
print(x2)
x3

[1 2 3 4]
[5 6]


array([7, 8, 9])

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>

 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>

 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>

 [[  11.],<br/>
  [ 15.]]].<br/>  

In [23]:
# prompt:  Let x be an array
# [[[ 0., 1., 2., 3.],
# [ 4., 5., 6., 7.]],
# [[ 8., 9., 10., 11.],
# [ 12., 13., 14., 15.]]].

x = np.array([[[ 0.,  1.,  2.,  3.],
              [ 4.,  5.,  6.,  7.]],

             [[ 8.,  9., 10., 11.],
              [12., 13., 14., 15.]]])

split_index = 3  # Split before the 4th column (index 3)
x1, x2 = np.split(x, [split_index], axis=2)

print(x1)
x2

[[[ 0.  1.  2.]
  [ 4.  5.  6.]]

 [[ 8.  9. 10.]
  [12. 13. 14.]]]


array([[[ 3.],
        [ 7.]],

       [[11.],
        [15.]]])

Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [24]:
# prompt: 12. Let x be an array
# [[ 0., 1., 2., 3.],
# [ 4., 5., 6., 7.],
# [ 8., 9., 10., 11.],
# [ 12., 13., 14., 15.]].
# Split it into two arrays along the second axis.

x = np.array([[ 0.,  1.,  2.,  3.],
              [ 4.,  5.,  6.,  7.],
              [ 8.,  9., 10., 11.],
              [12., 13., 14., 15.]])

# Split along the second axis (axis=1). By default, np.split divides
# the array into equal parts. To split into two, we need to specify
# the number of sections or the indices to split after.
# Since the second axis has size 4, splitting into two means each part
# will have size 2. The split point is after the second column (index 2).
x1, x2 = np.split(x, 2, axis=1)

print("First split array:")
print(x1)
print("\nSecond split array:")
x2


First split array:
[[ 0.  1.]
 [ 4.  5.]
 [ 8.  9.]
 [12. 13.]]

Second split array:


array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [25]:
# prompt: Let x be an array
# [[ 0., 1., 2., 3.],
# [ 4., 5., 6., 7.],
# [ 8., 9., 10., 11.],
# [ 12., 13., 14., 15.]].
# Split it into two arrays along the first axis.

# Split along the first axis (axis=0). By default, np.split divides
# the array into equal parts. To split into two, we need to specify
# the number of sections or the indices to split after.
# Since the first axis has size 4, splitting into two means each part
# will have size 2. The split point is after the second row (index 2).
x1, x2 = np.split(x, 2, axis=0)

print("First split array:")
print(x1)
print("\nSecond split array:")
x2

First split array:
[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]

Second split array:


array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [26]:
# prompt: Let x be an array [0, 1, 2]. Convert it to
# [[0, 1, 2, 0, 1, 2],
# [0, 1, 2, 0, 1, 2]].

x = np.array([0, 1, 2])

# Repeat the array twice horizontally using tile, then repeat the result twice vertically
result = np.tile(np.tile(x, 2), (2, 1))

result


array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [27]:
# prompt: Let x be an array [0, 1, 2]. Convert it to
# [0, 0, 1, 1, 2, 2].

x = np.array([0, 1, 2])
result = np.repeat(x, 2)
result

array([0, 0, 1, 1, 2, 2])

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [28]:
# prompt: Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].
# remove the leading the trailing zeros.

x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

# Find the index of the first non-zero element
first_nonzero = np.nonzero(x)[0][0]

# Find the index of the last non-zero element
last_nonzero = np.nonzero(x)[0][-1]

# Slice the array from the first non-zero to the last non-zero element
result = x[first_nonzero : last_nonzero + 1]

result

array([1, 2, 3, 0, 2, 1])

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [29]:
# prompt: Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.

x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])

# Get unique elements and their counts
unique_elements, counts = np.unique(x, return_counts=True)

print("Unique Elements:", unique_elements)
print("Counts:", counts)

Unique Elements: [1 2 3 4 5]
Counts: [2 3 1 1 2]


Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [30]:
# prompt: . Lex x be an array
# [[ 1 2]
# [ 3 4].
# Flip x along the second axis

x = np.array([[1, 2], [3, 4]])
x_flipped = np.flip(x, axis=1)
x_flipped


array([[2, 1],
       [4, 3]])

Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [31]:
# prompt: Lex x be an array
# [[ 1 2]
# [ 3 4].
# Flip x along the first axis.

x = np.array([[1, 2], [3, 4]])
x_flipped = np.flip(x, axis=0)
x_flipped

array([[3, 4],
       [1, 2]])

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [32]:
# prompt: . Lex x be an array
# [[ 1 2]
# [ 3 4].
# Rotate x 90 degrees counter-clockwise.

x = np.array([[1, 2], [3, 4]])
x_rotated = np.rot90(x, k=1) # k=1 for 90 degrees counter-clockwise
x_rotated

array([[2, 4],
       [1, 3]])

Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [33]:
# prompt: Lex x be an array
# [[ 1 2 3 4]
# [ 5 6 7 8].
# Shift elements one step to right along the second axis.

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

# Create a new array of the same shape, initialized with the elements shifted.
# Elements shifted to the right along the second axis (columns).
# The last column will "wrap around" to the first column.
# Use np.roll with shift=1 and axis=1.
x_shifted = np.roll(x, shift=1, axis=1)
x_shifted

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])