<a href="https://colab.research.google.com/github/ajit-ai/Python/blob/main/numpy/numpy_exercise/8_Logic_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logic functions

In [24]:
import numpy as np

In [25]:
np.__version__

'2.0.2'

## Truth value testing


Q1. Let x be an arbitrary array. Return True if none of the elements of x is zero. Remind that 0 evaluates to False in python.


In [26]:
x = np.array([1,2,3])
print(x)

x = np.array([1,0,3])
print(x)
#

[1 2 3]
[1 0 3]


Q2. Let x be an arbitrary array. Return True if any of the elements of x is non-zero.

In [27]:
x = np.array([1,0,0])
print(x)

x = np.array([0,0,0])
print(x)

[1 0 0]
[0 0 0]


## Array contents


Q3. Predict the result of the following code.

In [28]:
x = np.array([1, 0, np.nan, np.inf])
np.isfinite(x)

array([ True,  True, False, False])

Q4. Predict the result of the following code.

In [29]:
x = np.array([1, 0, np.nan, np.inf])
np.isinf(x)

array([False, False, False,  True])

Q5. Predict the result of the following code.

In [30]:
x = np.array([1, 0, np.nan, np.inf])
np.isnan(x)

array([False, False,  True, False])

## Array type testing

Q6. Predict the result of the following code.

In [31]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.iscomplex(x)

array([ True, False, False, False, False,  True])

Q7. Predict the result of the following code.

In [32]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.isreal(x)

array([False,  True,  True,  True,  True, False])

Q8. Predict the result of the following code.

In [33]:
np.isscalar(3)
np.isscalar([3])
np.isscalar(True)

True

## Logical operations

Q9. Predict the result of the following code.

In [34]:
#print np.logical_and([True, False], [False, False])
#print np.logical_or([True, False, True], [True, False, False])
#print np.logical_xor([True, False, True], [True, False, False])
#print np.logical_not([True, False, 0, 1])


## Comparison

Q10. Predict the result of the following code.

In [35]:
#print np.allclose([3], [2.999999])
#print np.array_equal([3], [2.999999])

Q11. Write numpy comparison functions such that they return the results as you see.

In [36]:
x = np.array([4, 5])
y = np.array([2, 5])
#
#
#
#

Q12. Predict the result of the following code.

In [37]:
#print np.equal([1, 2], [1, 2.000001])
#print np.isclose([1, 2], [1, 2.000001])