In [ ]:
import numpy as np
import pandas as pd

list1 = [1,2,3,4]
list2 = [1,2,3,4,5,6,7,8,9,10]

array1 = np.array(list1)
print(array1)



[1 2 3 4]


In [4]:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [5]:
list3 = [1,2,3,4,5,6,7,8,9,10] 
print(list3)

array3 = np.add(3,5)

print(array3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
8


In [6]:
import numpy as np

# Sample rocket velocity and acceleration vectors (m/s, m/s^2)
velocity = np.array([100, 200, 300])  # x, y, z components
acceleration = np.array([10, 5, 2])   # x, y, z components
time_step = 0.1  # seconds

# Calculate new velocity after time step: v_new = v + a * t
new_velocity = velocity + acceleration * time_step

# Compute magnitude of new velocity (speed)
speed = np.linalg.norm(new_velocity)

print("Initial Velocity:", velocity)
print("New Velocity:", new_velocity)
print("Speed (m/s):", speed)

# Matrix operation: rotation matrix to adjust trajectory (90-degree rotation around z-axis)
rotation_matrix = np.array([[0, -1, 0],
                           [1, 0, 0],
                           [0, 0, 1]])
rotated_velocity = np.dot(rotation_matrix, new_velocity)

print("Rotated Velocity:", rotated_velocity)

Initial Velocity: [100 200 300]
New Velocity: [101.  200.5 300.2]
Speed (m/s): 374.86169449544985
Rotated Velocity: [-200.5  101.   300.2]


In [7]:
import numpy as np

# Create a Python list
my_list = [1, 2, 3, 4, 5]

# Convert the Python list to a NumPy ndarray
my_array = np.array(my_list)

# Print the NumPy array
print(my_array)

[1 2 3 4 5]


In [9]:
import numpy as np

# Define the shape of the array
shape = (3, 4)  # Example: 3 rows, 4 columns

# Define the data type
dtype = np.float64  # Example: 64-bit floating point

# Initialize the array with zeros and set the data type
array = np.zeros(shape, dtype=dtype)

# You can also initialize with ones, random values, etc. as needed
# For example:
# array = np.ones(shape, dtype=dtype)
# array = np.random.rand(*shape)  # Initialize with random values between 0 and 1

print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

a = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)
print(a)



[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]


In [11]:
a = np.empty(2, dtype=object)
a[0] = np.array([1, 2, 3, 4, 5, 6])
a[1] = np.array([7, 8, 9])
print(a)

[array([1, 2, 3, 4, 5, 6]) array([7, 8, 9])]


In [12]:
import numpy as np

# Define the length of the array
length = 10

# Create the array filled with zeros
array = np.zeros(length, dtype=np.int32)

print(array)

[0 0 0 0 0 0 0 0 0 0]


In [13]:
import numpy as np

# Define the shape of the array
shape = (3, 5)

# Create the array filled with ones
array = np.ones(shape, dtype=np.float64)

print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
import numpy as np

# Create the array with the specified sequence
array = np.arange(0, 56, 4)

print(array)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52]


In [15]:
import numpy as np

# Create the array with five values evenly spaced between 0 and 1
array = np.linspace(0, 1, 5)

print(array)

[0.   0.25 0.5  0.75 1.  ]


In [16]:
import numpy as np

# Define the shape of the array
shape = (3, 3)

# Define the range for the uniform distribution
low = 0  # Lower bound
high = 1  # Upper bound

# Create the array with uniformly distributed random numbers
array = np.random.uniform(low, high, shape)

print(array)

[[0.53033038 0.71519493 0.93372484]
 [0.85805977 0.43139092 0.10448539]
 [0.5751927  0.18442394 0.31160029]]


In [17]:
import numpy as np

# Define the shape of the array
shape = (3, 3)

# Define the mean and standard deviation
mean = 0
std_dev = 1

# Create the array with normally distributed random numbers
array = np.random.normal(mean, std_dev, shape)

print(array)


[[ 0.56076565  0.55252021  0.24458798]
 [ 0.74199522  0.3505317  -0.66943545]
 [-0.71984147 -0.89418449 -0.32698031]]


In [18]:
import numpy as np

# Define the shape of the array
shape = (3, 3)

# Define the interval [0, 10)
low = 0
high = 10

# Create the array with pseudorandom integers
array = np.random.randint(low, high, shape)

print(array)

[[3 4 9]
 [2 9 6]
 [4 6 6]]


In [19]:
import numpy as np

# Create the 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
import numpy as np

# Create an uninitialized array of three integers
array = np.empty(3, dtype=int)

print(array)

[632976416       570         0]


In [21]:
import numpy as np

# Create an ndarray of integers with specified data type
array_int = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Create an ndarray of floating-point numbers with specified data type
array_float = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)

# Create an ndarray of complex numbers with specified data type
array_complex = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)

print("Array of integers (dtype=np.int32):")
print(array_int)
print("\nArray of floating-point numbers (dtype=np.float64):")
print(array_float)
print("\nArray of complex numbers (dtype=np.complex128):")
print(array_complex)

Array of integers (dtype=np.int32):
[1 2 3 4 5]

Array of floating-point numbers (dtype=np.float64):
[1.1 2.2 3.3 4.4 5.5]

Array of complex numbers (dtype=np.complex128):
[1.+2.j 3.+4.j 5.+6.j]


In [22]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the number of dimensions of the array
num_dimensions = array.ndim

print("Number of dimensions:", num_dimensions)

Number of dimensions: 2


In [23]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array
shape = array.shape

# Get the size of each dimension
size_of_dimensions = shape[0], shape[1]  # Assuming a 2-dimensional array

print("Size of each dimension:", size_of_dimensions)

Size of each dimension: (2, 3)


In [24]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the total size of the array
total_size = array.size

print("Total size of the array:", total_size)

Total size of the array: 6


In [25]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the data type of the elements in the array
element_type = array.dtype

print("Data type of each element:", element_type)

Data type of each element: int32


In [26]:
import numpy as np

# Create a single-dimensional NumPy ndarray
array = np.array([1, 2, 3, 4, 5])

# Access single elements using indexing
element_at_index_0 = array[0]
element_at_index_2 = array[2]
last_element = array[-1]  # Negative index counts from the end

print("Element at index 0:", element_at_index_0)
print("Element at index 2:", element_at_index_2)
print("Last element:", last_element)

Element at index 0: 1
Element at index 2: 3
Last element: 5


In [27]:
import numpy as np

# Create a multidimensional NumPy ndarray
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Access a single element using comma-separated indices
element = array[1, 2]  # Accesses the element at row 1, column 2

print("Element at row 1, column 2:", element)

Element at row 1, column 2: 6


In [28]:
import numpy as np

# Create a multidimensional NumPy ndarray
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Access and modify a single element using comma-separated indices
array[1, 2] = 10  # Modifying the element at row 1, column 2 to 10

print("Modified array:")
print(array)

Modified array:
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


In [29]:
import numpy as np

# Create a 2-dimensional NumPy ndarray
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Access a subarray (slice) using slice notation
subarray = array[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2

print("Subarray:")
print(subarray)

Subarray:
[[2 3]
 [5 6]]


In [30]:
import numpy as np

# Create a one-dimensional NumPy ndarray
array = np.array([1, 2, 3, 4, 5])

# Get the subarray of the first three elements using slicing
subarray = array[3:]

print("Subarray of the first three elements:")
print(subarray)

Subarray of the first three elements:
[4 5]


In [31]:
# Enter your code here. Read input from STDIN. Print output to STDOUT


a = int(input())
b = int(input())
c = int(input())
d = int(input())

result = (a ** b) + (c ** d)
print(result)

5780426


In [32]:
for i in range(1,int(input())): #More than 2 lines will result in 0 score. Do not leave a blank line also
    print((10**i // 9) * i)
       

1
22
333
4444
55555


In [ ]:
import xml.etree.ElementTree as ET

n = int(input())
xml_lines = [input() for _ in range(n
                                    )]
xml_string = "\n".join(xml_lines)

root = ET.fromstring(xml_string)

def max_depth(elem, depth=0):
    if len(elem) == 0:
        return depth
    return max(max_depth(child, depth + 1) for child in elem)

print(max_depth(root))

In [34]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    # your code goes here
    
    maxdepth = max(maxdepth, level + 1)
    
    for child in elem:
        depth(child, level + 1)
  

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

ParseError: syntax error: line 1, column 0 (<string>)