In [3]:
import numpy as np

In [2]:
%pip install numpy

  Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB 131.3 kB/s eta 0:01:38
   ---------------------------------------- 0.0/12.8 MB 131.3 kB/s eta 0:01:38
   ---------------------------------------- 0.0/12.8 MB 119.1 kB/s eta 0:01:48
   ---------------------------------------- 0.1/12.8 MB 187.0 kB/s eta 0:01:09
   ---------------------------------------- 0.1/12.8 MB 204.8 kB/s eta 0:01:03
   ---------------------------------------- 0.1/12.8 MB 206.9 kB/s eta 0:01:02
   ---------------------------------------- 0.1/12.8 MB 256.7 kB/s eta 0:00:50
   ---------------------------------------- 0.1/12.8 MB 288.1 kB/s eta 0:00:44
   ---------------------------------------- 0.1/12.8 MB 315.4 kB/s eta 0:00:41
   ------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
print(np.__version__)
np.show_config()

2.3.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35213",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35213",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sokdaj8v/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [10]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [12]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.008071059959777416 0.9960307286615263


In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.49936269812117307


In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [18]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [20]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [25]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.87706061  0.24274549  0.84744128 -0.79057509  1.7727782 ]
 [ 0.05096155 -0.99384453 -0.37450533  0.01014836 -0.90847114]
 [-0.10828199 -0.4788096  -0.38906115 -1.19269214 -1.06076452]
 [ 1.57838751 -0.31332368  1.44160388 -1.00398783 -1.27198032]
 [ 0.85311838 -1.15228863 -0.70075912  1.21021891  0.85488089]]


In [29]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [30]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [31]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [32]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [33]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [34]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [36]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\ajitj\AppData\Local\Temp\ipykernel_9808\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\ajitj\AppData\Local\Temp\ipykernel_9808\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\ajitj\AppData\Local\Temp\ipykernel_9808\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

In [37]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\ajitj\AppData\Local\Temp\ipykernel_9808\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\ajitj\AppData\Local\Temp\ipykernel_9808\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\ajitj\AppData\Local\Temp\ipykernel_9808\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [38]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-6.  7.  7.  2.  8.  5. -5. 10. -5. 10.]
[-6.  7.  7.  2.  8.  5. -5. 10. -5. 10.]


In [39]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 4 5 6]


In [40]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [45]:
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1) == np.emath.sqrt(-1)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

2025-06-30
2025-07-01
2025-07-02
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [47]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[7. 5. 7. 3. 6. 5. 7. 1. 4. 7.]
[7. 5. 7. 3. 6. 5. 7. 1. 4. 7.]
[7. 5. 7. 3. 6. 5. 7. 1. 4. 7.]
[7 5 7 3 6 5 7 1 4 7]
[7. 5. 7. 3. 6. 5. 7. 1. 4. 7.]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [49]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [51]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [52]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00847946 0.22848106 0.268876   0.38299654 0.72779573 0.80458339
 0.85543005 0.8926948  0.90441056 0.97155111]


In [53]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [55]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.37706531 0.72771532 0.39638034 0.96826065 0.86884196 0.8075709
 0.82011651 0.49891329 0.66223721 1.26098301]
[0.76973824 0.5652029  0.97341195 0.25448241 0.88674977 1.23838468
 0.27115419 1.03431142 0.73496962 0.78949442]


In [56]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.41789662 0.48104718 0.56403057 0.42911317 0.         0.72506554
 0.74779215 0.21689644 0.83242929 0.78892169]


In [57]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [58]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [59]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [60]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

25


In [62]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\ajitj\AppData\Local\Temp\ipykernel_9808\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [65]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.33847231 0.54546755 0.10239512 0.18194759]
 [0.33847231 0.         0.62962562 0.39092786 0.15744284]
 [0.54546755 0.62962562 0.         0.45570384 0.57947907]
 [0.10239512 0.39092786 0.45570384 0.         0.24661776]
 [0.18194759 0.15744284 0.57947907 0.24661776 0.        ]]
[[0.         0.28227078 0.33184453 0.42593615 0.17893188 0.73350503
  0.44696771 0.28288863 0.73723548 0.25703379]
 [0.28227078 0.         0.52113941 0.15092723 0.24357739 0.51128576
  0.61452999 0.50779515 0.49803755 0.30920893]
 [0.33184453 0.52113941 0.         0.66911134 0.27865502 1.02674599
  0.71088193 0.08077609 1.01823927 0.58816824]
 [0.42593615 0.15092723 0.66911134 0.         0.39048096 0.37976437
  0.69380547 0.6584379  0.3573335  0.38100427]
 [0.17893188 0.24357739 0.27865502 0.39048096 0.         0.75323188
  0.62455237 0.27568892 0.7415924  0.39424003]
 [0.73350503 0.51128576 1.02674599 0.37976437 0.75323188 0.
  0.80594276 1.00216623 0.06395105 0.55828788]
 [0.44696771 0.61452999 0.7

In [66]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[68 24  4 44 56 21 38 25 19  3]


In [69]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [70]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [71]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [72]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.2957433  -0.47087458  0.16876694  0.04434559  0.15328319 -0.48048259
   0.28291038  0.04735931 -0.33118111  0.29012957]
 [-0.31867027 -0.38878455 -0.01881747  0.31613532  0.2085552   0.39141058
  -0.06440729 -0.52153421  0.08174402  0.31436868]
 [ 0.03386367  0.39194333 -0.50195533  0.31052661  0.14317111  0.23954413
   0.27461183 -0.58913184  0.14079438 -0.44336789]
 [-0.25725473  0.01296348  0.48433837  0.19603416  0.52321368  0.44088137
  -0.36824309 -0.45161657 -0.3827283  -0.19758836]
 [-0.19275481 -0.29462129  0.03488358 -0.11222137 -0.06153181  0.3535843
  -0.01478047  0.32902723  0.28902718 -0.33061255]]


In [73]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 7 1]
 [1 2 5]
 [7 6 1]]
[[1 2 5]
 [7 6 1]
 [8 7 1]]


In [74]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


In [75]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4924429136997418


In [76]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [77]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [78]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[4. 2. 4. 4. 4. 2. 1. 4. 3. 2.]
[7. 3. 7. 7. 7. 3. 1. 7. 5. 3.]


In [79]:

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [80]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


In [81]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 53 46 80]
 [38 51 60 57]
 [44 63 50 65]]
[[44 53 46 80]
 [38 51 60 57]
 [44 63 50 65]]


In [82]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.68365002 0.49411688 0.2708444  0.53298845 0.5134433  0.51609181
 0.37117325 0.4719426  0.4954815  0.64301806]
0    0.683650
1    0.494117
2    0.270844
3    0.532988
4    0.513443
5    0.516092
6    0.371173
7    0.471943
8    0.495482
9    0.643018
dtype: float64


In [83]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.45917324, 1.44698934, 1.69221914, 1.42986892, 1.6718321 ])

In [84]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [85]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [86]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [87]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 80) ( 2, 87) ( 3, 10) ( 3, 30) ( 3, 86) ( 4, 25) ( 4, 41) ( 4, 45)
 ( 4, 53) ( 8, 38) ( 8, 74) (10, 10) (25, 41) (30, 44) (30, 86) (30, 99)
 (38, 74) (44, 96) (44, 98) (44, 99) (45, 53) (53, 58) (53, 69) (57, 72)
 (57, 78) (58, 69) (72, 78) (80, 87) (96, 98)]


In [88]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [89]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [90]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [91]:

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.87101039, -0.26924462, -0.64897617, -0.103252  , -0.318062  ,
        0.51513896,  0.2211025 , -0.31179235, -0.20869774, -0.05977574,
        0.68731633, -0.23479586, -0.83013181,  0.18774049,  0.83000496,
       -0.06250776, -0.81983152,  0.34381504, -0.47881996, -0.08966611,
       -0.30756514,  0.94468735, -0.37903757, -0.902089  , -0.29961722,
        0.24749526,  0.4266778 ,  0.98657407,  0.5805262 , -0.18666717,
       -0.02689517,  0.7915642 ,  0.98112821, -0.84887699,  0.5385369 ,
        0.70592184, -0.02425907, -0.77818399, -0.78702749, -0.53669865,
       -0.09143492,  0.79099912, -0.37009575, -0.09679233, -0.31272661,
        0.57953485, -0.18428969, -0.9875277 ,  0.03213349, -0.03942267,
        0.60869636,  0.44541291, -0.89918494, -0.09394685,  0.9073099 ,
       -0.06910798, -0.81935635,  0.41034739, -0.3774576 ,  0.72874762,
        0.84604693, -0.79700776,  0.62961942, -0.44791625,  0.94405082,
       -0.28778172, -0.48199754, -0.49740953,  0.07985243, -0.30

In [92]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.48086681 12.49459428  1.71779027  2.07495434  7.57886361  3.81908546
  1.22007967  1.33625808  1.59859427 11.02259587]


In [93]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.52883831  7.55805508  1.53727382  0.46037159  7.19575625  1.89890251
   6.72322037  6.34403152  3.24526315  0.88844149]
 [ 3.6036362   8.93298801  4.24836954  1.94250251  4.70532005  4.83234172
   9.17958622  1.29112931  3.89195941  7.77787116]
 [ 9.69760347  1.52266134  1.13638823  5.28692369  2.21096744 11.56882911
   1.96345675  2.6495285   6.61144638 10.97360544]
 [ 9.89065061 16.95060804  3.79845362  8.3725823  17.13637962  7.94129344
  15.52190801 10.52005502  9.07009828  5.49042541]
 [ 7.91935334 17.09042002  5.79739163  8.9297529  15.77100723  6.41015006
  16.10100935  7.41926607  6.09226292  2.58477161]
 [ 0.58203956 15.44423242 10.04286864  8.53054954  9.94434695  0.15772056
  15.76837796  1.84924744  3.19962659  6.63166506]
 [ 2.79302863  9.37142037  0.92253243  1.15283318  9.44243234  0.36393514
   8.3249532   7.83475688  5.03301824  0.99244138]
 [ 3.56394343  5.74028317  0.49551667  1.70980535  3.63646093  5.61629324
   5.5046698   2.11766406  1.19385324  5.36568806]


In [95]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
#R[r] = Z[z]
print(Z)
print(R)

[[7 4 4 7 7 7 3 9 1 8]
 [9 5 8 1 2 8 1 1 9 3]
 [7 7 7 1 0 4 2 6 3 5]
 [3 8 1 5 4 4 7 0 4 9]
 [5 2 9 9 1 7 9 3 6 0]
 [7 5 0 9 1 6 6 5 8 3]
 [6 0 4 5 4 0 7 9 3 8]
 [5 7 0 6 8 2 3 4 7 0]
 [7 3 3 5 7 7 0 2 9 9]
 [7 6 8 2 2 6 1 9 9 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [96]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
Z = np.random.uniform(0,1,(10,10))
print(Z)

U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

rank = np.linalg.matrix_rank(Z)
print(rank)

[[0.26686826 0.31083181 0.60241056 0.48699147 0.21345583 0.50839267
  0.97069836 0.07444415 0.74517387 0.15506996]
 [0.50855839 0.48303048 0.27221605 0.47602137 0.52004716 0.30920864
  0.17651673 0.78420931 0.35738392 0.06997452]
 [0.45666712 0.46473717 0.18468492 0.83567901 0.31364474 0.15380258
  0.82912614 0.81179337 0.54812309 0.19476727]
 [0.60016201 0.14510643 0.86492477 0.0636435  0.49106308 0.29917926
  0.59505805 0.52784842 0.76557379 0.63058591]
 [0.11886117 0.64917833 0.97220104 0.24194741 0.20675324 0.61003458
  0.96891124 0.17077423 0.1131017  0.24379668]
 [0.01252777 0.57491605 0.6222727  0.76421371 0.09209785 0.74728837
  0.86870396 0.51745596 0.83445991 0.95385641]
 [0.10811416 0.01206299 0.93506265 0.08544611 0.48511057 0.43630687
  0.50932358 0.16325183 0.38823027 0.00207239]
 [0.33127083 0.63006465 0.28556859 0.82320081 0.0836573  0.49465126
  0.99233612 0.53084462 0.59402445 0.44749383]
 [0.29919713 0.59210942 0.55736494 0.9062268  0.67816648 0.05495831
  0.25969444

In [101]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [102]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[1 4 0]
   [0 0 2]
   [3 0 3]]

  [[4 0 1]
   [0 2 0]
   [0 3 0]]

  [[0 1 4]
   [2 0 3]
   [3 0 2]]

  [[1 4 0]
   [0 3 4]
   [0 2 4]]

  [[4 0 4]
   [3 4 4]
   [2 4 0]]

  [[0 4 1]
   [4 4 1]
   [4 0 1]]

  [[4 1 3]
   [4 1 2]
   [0 1 2]]

  [[1 3 1]
   [1 2 1]
   [1 2 0]]]


 [[[0 0 2]
   [3 0 3]
   [3 1 2]]

  [[0 2 0]
   [0 3 0]
   [1 2 2]]

  [[2 0 3]
   [3 0 2]
   [2 2 3]]

  [[0 3 4]
   [0 2 4]
   [2 3 4]]

  [[3 4 4]
   [2 4 0]
   [3 4 1]]

  [[4 4 1]
   [4 0 1]
   [4 1 3]]

  [[4 1 2]
   [0 1 2]
   [1 3 0]]

  [[1 2 1]
   [1 2 0]
   [3 0 3]]]


 [[[3 0 3]
   [3 1 2]
   [0 2 4]]

  [[0 3 0]
   [1 2 2]
   [2 4 3]]

  [[3 0 2]
   [2 2 3]
   [4 3 0]]

  [[0 2 4]
   [2 3 4]
   [3 0 2]]

  [[2 4 0]
   [3 4 1]
   [0 2 0]]

  [[4 0 1]
   [4 1 3]
   [2 0 1]]

  [[0 1 2]
   [1 3 0]
   [0 1 0]]

  [[1 2 0]
   [3 0 3]
   [1 0 3]]]


 [[[3 1 2]
   [0 2 4]
   [3 4 3]]

  [[1 2 2]
   [2 4 3]
   [4 3 2]]

  [[2 2 3]
   [4 3 0]
   [3 2 3]]

  [[2 3 4]
   [3 0 2]
   [2 3 4]]

  [[3 4 1]
   

In [103]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  4 13 10  7]
 [ 4  5  5  8  6]
 [13  5  3 42  9]
 [10  8 42  7  8]
 [ 7  6  9  8  2]]


In [104]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [106]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
print(S)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [107]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  1 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 1 1 1 1 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 1 1 1 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1
  1 0 1 1 1 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
  1 1 0 0 1 1 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0

In [108]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


In [109]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [111]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.13 s ± 517 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
754 ms ± 125 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
361 ms ± 27.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [110]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [112]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 7]


In [114]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 0 0]
 [1 1 4]
 [1 3 0]
 [3 1 0]
 [3 3 3]
 [3 1 3]
 [1 2 0]
 [2 4 3]
 [0 1 4]
 [2 3 0]]
[[4 0 0]
 [1 1 4]
 [1 3 0]
 [3 1 0]
 [3 1 3]
 [1 2 0]
 [2 4 3]
 [0 1 4]
 [2 3 0]]
[[4 0 0]
 [1 1 4]
 [1 3 0]
 [3 1 0]
 [3 1 3]
 [1 2 0]
 [2 4 3]
 [0 1 4]
 [2 3 0]]


In [116]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [118]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]]


In [119]:

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[2.16187600e-01, 2.22123307e-01, 1.52445186e-01, 3.07408005e-01,
        5.56715014e-02, 1.72932333e-02, 5.78754060e-01, 3.50223009e-01,
        1.39262027e-01, 3.91301548e-01],
       [8.57720087e-04, 8.81269891e-04, 6.04823303e-04, 1.21963527e-03,
        2.20875596e-04, 6.86105660e-05, 2.29619545e-03, 1.38950296e-03,
        5.52519378e-04, 1.55248126e-03],
       [1.82865829e-03, 1.87886644e-03, 1.28948262e-03, 2.60026105e-03,
        4.70906530e-04, 1.46277652e-04, 4.89548619e-03, 2.96241879e-03,
        1.17797071e-03, 3.30988836e-03],
       [1.42725043e-01, 1.46643742e-01, 1.00642894e-01, 2.02947906e-01,
        3.67538075e-02, 1.14168318e-02, 3.82088048e-01, 2.31213974e-01,
        9.19394955e-02, 2.58333643e-01],
       [1.57242500e-01, 1.61559795e-01, 1.10879913e-01, 2.23591008e-01,
        4.04922673e-02, 1.25781092e-02, 4.20952615e-01, 2.54732194e-01,
        1.01291237e-01, 2.84610375e-01],
       [1.79030379e-01, 1.83945887e-01, 1.26243685e-01, 2.54572286e-01,
   

In [121]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

print(x_int)
print(y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

In [122]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [123]:

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.0928332   0.30600453]


In [100]:
import numpy as np
import pandas as pd

list1 = [1,2,3,4]
list2 = [1,2,3,4,5,6,7,8,9,10]

array1 = np.array(list1)
print(array1)


[1 2 3 4]


In [4]:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [5]:
list3 = [1,2,3,4,5,6,7,8,9,10] 
print(list3)

array3 = np.add(3,5)

print(array3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
8


In [6]:
import numpy as np

# Sample rocket velocity and acceleration vectors (m/s, m/s^2)
velocity = np.array([100, 200, 300])  # x, y, z components
acceleration = np.array([10, 5, 2])   # x, y, z components
time_step = 0.1  # seconds

# Calculate new velocity after time step: v_new = v + a * t
new_velocity = velocity + acceleration * time_step

# Compute magnitude of new velocity (speed)
speed = np.linalg.norm(new_velocity)

print("Initial Velocity:", velocity)
print("New Velocity:", new_velocity)
print("Speed (m/s):", speed)

# Matrix operation: rotation matrix to adjust trajectory (90-degree rotation around z-axis)
rotation_matrix = np.array([[0, -1, 0],
                           [1, 0, 0],
                           [0, 0, 1]])
rotated_velocity = np.dot(rotation_matrix, new_velocity)

print("Rotated Velocity:", rotated_velocity)

Initial Velocity: [100 200 300]
New Velocity: [101.  200.5 300.2]
Speed (m/s): 374.86169449544985
Rotated Velocity: [-200.5  101.   300.2]


In [7]:
import numpy as np

# Create a Python list
my_list = [1, 2, 3, 4, 5]

# Convert the Python list to a NumPy ndarray
my_array = np.array(my_list)

# Print the NumPy array
print(my_array)

[1 2 3 4 5]


In [9]:
import numpy as np

# Define the shape of the array
shape = (3, 4)  # Example: 3 rows, 4 columns

# Define the data type
dtype = np.float64  # Example: 64-bit floating point

# Initialize the array with zeros and set the data type
array = np.zeros(shape, dtype=dtype)

# You can also initialize with ones, random values, etc. as needed
# For example:
# array = np.ones(shape, dtype=dtype)
# array = np.random.rand(*shape)  # Initialize with random values between 0 and 1

print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

a = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)
print(a)



[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]


In [11]:
a = np.empty(2, dtype=object)
a[0] = np.array([1, 2, 3, 4, 5, 6])
a[1] = np.array([7, 8, 9])
print(a)

[array([1, 2, 3, 4, 5, 6]) array([7, 8, 9])]


In [12]:
import numpy as np

# Define the length of the array
length = 10

# Create the array filled with zeros
array = np.zeros(length, dtype=np.int32)

print(array)

[0 0 0 0 0 0 0 0 0 0]


In [13]:
import numpy as np

# Define the shape of the array
shape = (3, 5)

# Create the array filled with ones
array = np.ones(shape, dtype=np.float64)

print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
import numpy as np

# Create the array with the specified sequence
array = np.arange(0, 56, 4)

print(array)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52]


In [15]:
import numpy as np

# Create the array with five values evenly spaced between 0 and 1
array = np.linspace(0, 1, 5)

print(array)

[0.   0.25 0.5  0.75 1.  ]


In [16]:
import numpy as np

# Define the shape of the array
shape = (3, 3)

# Define the range for the uniform distribution
low = 0  # Lower bound
high = 1  # Upper bound

# Create the array with uniformly distributed random numbers
array = np.random.uniform(low, high, shape)

print(array)

[[0.53033038 0.71519493 0.93372484]
 [0.85805977 0.43139092 0.10448539]
 [0.5751927  0.18442394 0.31160029]]


In [17]:
import numpy as np

# Define the shape of the array
shape = (3, 3)

# Define the mean and standard deviation
mean = 0
std_dev = 1

# Create the array with normally distributed random numbers
array = np.random.normal(mean, std_dev, shape)

print(array)


[[ 0.56076565  0.55252021  0.24458798]
 [ 0.74199522  0.3505317  -0.66943545]
 [-0.71984147 -0.89418449 -0.32698031]]


In [18]:
import numpy as np

# Define the shape of the array
shape = (3, 3)

# Define the interval [0, 10)
low = 0
high = 10

# Create the array with pseudorandom integers
array = np.random.randint(low, high, shape)

print(array)

[[3 4 9]
 [2 9 6]
 [4 6 6]]


In [19]:
import numpy as np

# Create the 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
import numpy as np

# Create an uninitialized array of three integers
array = np.empty(3, dtype=int)

print(array)

[632976416       570         0]


In [21]:
import numpy as np

# Create an ndarray of integers with specified data type
array_int = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Create an ndarray of floating-point numbers with specified data type
array_float = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)

# Create an ndarray of complex numbers with specified data type
array_complex = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)

print("Array of integers (dtype=np.int32):")
print(array_int)
print("\nArray of floating-point numbers (dtype=np.float64):")
print(array_float)
print("\nArray of complex numbers (dtype=np.complex128):")
print(array_complex)

Array of integers (dtype=np.int32):
[1 2 3 4 5]

Array of floating-point numbers (dtype=np.float64):
[1.1 2.2 3.3 4.4 5.5]

Array of complex numbers (dtype=np.complex128):
[1.+2.j 3.+4.j 5.+6.j]


In [22]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the number of dimensions of the array
num_dimensions = array.ndim

print("Number of dimensions:", num_dimensions)

Number of dimensions: 2


In [23]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array
shape = array.shape

# Get the size of each dimension
size_of_dimensions = shape[0], shape[1]  # Assuming a 2-dimensional array

print("Size of each dimension:", size_of_dimensions)

Size of each dimension: (2, 3)


In [24]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the total size of the array
total_size = array.size

print("Total size of the array:", total_size)

Total size of the array: 6


In [25]:
import numpy as np

# Create a NumPy ndarray
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the data type of the elements in the array
element_type = array.dtype

print("Data type of each element:", element_type)

Data type of each element: int32


In [26]:
import numpy as np

# Create a single-dimensional NumPy ndarray
array = np.array([1, 2, 3, 4, 5])

# Access single elements using indexing
element_at_index_0 = array[0]
element_at_index_2 = array[2]
last_element = array[-1]  # Negative index counts from the end

print("Element at index 0:", element_at_index_0)
print("Element at index 2:", element_at_index_2)
print("Last element:", last_element)

Element at index 0: 1
Element at index 2: 3
Last element: 5


In [27]:
import numpy as np

# Create a multidimensional NumPy ndarray
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Access a single element using comma-separated indices
element = array[1, 2]  # Accesses the element at row 1, column 2

print("Element at row 1, column 2:", element)

Element at row 1, column 2: 6


In [28]:
import numpy as np

# Create a multidimensional NumPy ndarray
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Access and modify a single element using comma-separated indices
array[1, 2] = 10  # Modifying the element at row 1, column 2 to 10

print("Modified array:")
print(array)

Modified array:
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


In [29]:
import numpy as np

# Create a 2-dimensional NumPy ndarray
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Access a subarray (slice) using slice notation
subarray = array[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2

print("Subarray:")
print(subarray)

Subarray:
[[2 3]
 [5 6]]


In [30]:
import numpy as np

# Create a one-dimensional NumPy ndarray
array = np.array([1, 2, 3, 4, 5])

# Get the subarray of the first three elements using slicing
subarray = array[3:]

print("Subarray of the first three elements:")
print(subarray)

Subarray of the first three elements:
[4 5]


In [31]:
# Enter your code here. Read input from STDIN. Print output to STDOUT


a = int(input())
b = int(input())
c = int(input())
d = int(input())

result = (a ** b) + (c ** d)
print(result)

5780426


In [2]:
for i in range(1,int(input())): #More than 2 lines will result in 0 score. Do not leave a blank line also
    print((10**i // 9) * i)
       

1
22
333
4444
55555
666666
7777777
88888888
999999999
11111111110
122222222221
1333333333332
14444444444443
155555555555554
1666666666666665
17777777777777776
188888888888888887
1999999999999999998
21111111111111111109
222222222222222222220
2333333333333333333331
24444444444444444444442
255555555555555555555553
2666666666666666666666664
27777777777777777777777775
288888888888888888888888886
2999999999999999999999999997
31111111111111111111111111108
322222222222222222222222222219
3333333333333333333333333333330
34444444444444444444444444444441
355555555555555555555555555555552
3666666666666666666666666666666663
37777777777777777777777777777777774
388888888888888888888888888888888885
3999999999999999999999999999999999996
41111111111111111111111111111111111107
422222222222222222222222222222222222218
4333333333333333333333333333333333333329
44444444444444444444444444444444444444440
455555555555555555555555555555555555555551
4666666666666666666666666666666666666666662
4777777777777777777777

In [4]:

import numpy as np

myArray = np.arange(20)
print(myArray)            

myArray = np.arange(10, 20) 
print(myArray)

myArray = np.arange(10, 20, 2)
print(myArray)             

myArray = np.arange(20)

myArray = myArray.reshape(4, 5)
print(myArray)

myArray = myArray.reshape(10, 2)
print(myArray)

# shape returns the shape of the array. The length of shape tuple is called as rank (or dimension)
print(myArray.shape)     

# ndim returns the dimension (rank) of the array
print(myArray.ndim)      

# size returns the total number of elements in the array
print(myArray.size)         # 20

# to check the data we have dtype.
print(myArray.dtype)        # int64

# zeros creates an array will all zeros
myArray = np.zeros((3, 4))
print(myArray)


# ones creates an array with all ones
myArray = np.ones((3, 4))
print(myArray)

# numpy random module helps to initialize array with random values
myArray = np.random.rand(3, 4)
print(myArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
(10, 2)
2
20
int32
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.24562611 0.26235936 0.660937   0.61726642]
 [0.70663628 0.12712534 0.13241955 0.66253491]
 [0.655638   0.87168543 0.91566784 0.70069023]]


In [5]:

import numpy as np

# while creating a numpy array, any data type from above can be explicitly specified.
myArray = np.arange(10)
print(myArray)         

myArray = np.array(myArray, dtype = np.float32)
print(myArray)         

myArray = np.array(myArray, dtype = np.complex64)
print(myArray)         


[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [10]:

import numpy as np

myArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(myArray)

print(myArray[0, 1]) # Accessing element at row 0, column 1
print(myArray[2, 2]) # Accessing element at row 2, column 2
print(myArray[1, 2])  # Accessing element at row 1,


# ndarray.size returns the number of items in the array
print(myArray.size)             

# ndarray.shape returns a tuple consisting of array dimensions
print(myArray.shape)            

# ndarray.ndim returns the number of array dimensions
print(myArray.ndim)            

# ndarray.itemsize returns the memory size of each element in the array
print(myArray.itemsize) 

# ndarray.nbytes returns the total number of bytes consumed by the elements of the array
print(myArray.nbytes)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
6
9
(3, 3)
2
4
36


In [11]:

import numpy as np

# ndarray.arange(start, stop, step, dtype)
# Creates a numpy array from 1 to 20
myArray = np.arange(1, 21)
print(myArray)                     

# Specifying data type of each element
myArray = np.arange(10, dtype = 'float')
print(myArray)                    

# Specifying steps to jump in between two elements
myArray = np.arange(1, 21, 2)
print(myArray)                    

# ndarray.linspace(start, stop, num, endpoint,  retstep, dtype)
# Shows 5 equal intervals between 10 to 20
myArray = np.linspace(10, 20, 5)
print(myArray)                     

# if endpoint is set to false the last number inn STOP parameter is not executed
myArray = np.linspace(10, 20, 5, endpoint = False)
print(myArray)                    

# ndarray.lopspace returns an ndarray object that contains the numbers that are evenly spaced
# on a log scale.
# ndarray.logscale(start, stop, num, endpoint, base, dtype)
# default base is 10
myArray = np.logspace(1.0, 3.0, num = 10)
print(myArray)


myArray = np.logspace(1.0, 3.0, num = 10, base = 2)
print(myArray)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1  3  5  7  9 11 13 15 17 19]
[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]
[  10.           16.68100537   27.82559402   46.41588834   77.42636827
  129.1549665   215.443469    359.38136638  599.48425032 1000.        ]
[2.         2.33305808 2.72158    3.1748021  3.70349885 4.32023896
 5.0396842  5.87893797 6.85795186 8.        ]


In [12]:
import numpy as np

# numpy.reshape(array_to_reshape, tuple_of_new_shape) gives new shape (dimension) to our array
myArray = np.arange(0, 30, 2)
print(myArray)             

myArrayReshaped = myArray.reshape(5, 3)
print(myArrayReshaped)

# numpy.ndarray.flat() returns an 1-D iterator
print(myArray.flat[5])      # 10

# numpy.ndarray.flatten() restores the reshaped array into a 1-D array
print(myArrayReshaped.flatten())

# numpy.tranpose() this helps to find the tranpose of the given array
print(myArrayReshaped.transpose())


# numpy.swapaxes(array, axis1, axis2) interchanges the two axes of an array
originalArray = np.arange(8).reshape(2,2,2)
print(originalArray)



print(np.swapaxes(originalArray, 2, 0))


# numpy.rollaxis(arr, axis, start) rolls the specified axis backwards, until it lies in a specified position
print(np.rollaxis(originalArray, 2))


# numpy.resize(arr, shape) returns a new array with the specified size. If the new size is greater than
# the original, the repeated copies of entries in the original are contained

myArray = np.array([[1,2,3],[4,5,6]])
print(myArray)


print(np.resize(myArray, (3, 2)))


# numpy.append(array, values, axis)
myArray = np.array([[1,2,3],[4,5,6]])
print(myArray)


print(np.append(myArray, [7, 8, 9]))


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]
10
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[[ 0  6 12 18 24]
 [ 2  8 14 20 26]
 [ 4 10 16 22 28]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]
