In [2]:
import numpy as np
import pandas as pd

list1 = [1,2,3,4]
list2 = [1,2,3,4,5,6,7,8,9,10]

array1 = np.array(list1)
print(array1)



[1 2 3 4]


In [3]:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [4]:
list3 = [1,2,3,4,5,6,7,8,9,10] 
print(list3)

array3 = np.add(3,5)

print(array3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
8


In [5]:
import numpy as np

# Sample rocket velocity and acceleration vectors (m/s, m/s^2)
velocity = np.array([100, 200, 300])  # x, y, z components
acceleration = np.array([10, 5, 2])   # x, y, z components
time_step = 0.1  # seconds

# Calculate new velocity after time step: v_new = v + a * t
new_velocity = velocity + acceleration * time_step

# Compute magnitude of new velocity (speed)
speed = np.linalg.norm(new_velocity)

print("Initial Velocity:", velocity)
print("New Velocity:", new_velocity)
print("Speed (m/s):", speed)

# Matrix operation: rotation matrix to adjust trajectory (90-degree rotation around z-axis)
rotation_matrix = np.array([[0, -1, 0],
                           [1, 0, 0],
                           [0, 0, 1]])
rotated_velocity = np.dot(rotation_matrix, new_velocity)

print("Rotated Velocity:", rotated_velocity)

Initial Velocity: [100 200 300]
New Velocity: [101.  200.5 300.2]
Speed (m/s): 374.86169449544985
Rotated Velocity: [-200.5  101.   300.2]
