In [7]:
import numpy as np
import pandas as pd

list1 = [1,2,3,4]
list2 = [1,2,3,4,5,6,7,8,9,10]

array1 = np.array(list1)
print(array1)



[1 2 3 4]


In [6]:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [5]:
list3 = [1,2,3,4,5,6,7,8,9,10] 
print(list3)

array3 = np.add(3,5)

print(array3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
8
